Namespace,Type,NOF,NOM,NOP,NOPF,NOPM,LOC,WMC,NC,DIT,LCOM,Fan-Out,Fan-In,Fan-Out types,Fan-In types
Rhino.Runtime,HostUtils,7,17,5,0,12,914,32,0,0,0.76,7,4,Rhino.Geometry.GeometryBase' Rhino.Runtime.InteropWrappers.StringHolder' Rhino.Geometry.BezierCurve' Rhino.Runtime.AssemblyResolver' Rhino.DocObjects.Custom.UserData' Rhino.DocObjects.Custom.UserDictionary' Rhino.DocObjects.Custom.SharedUserDictionary,Rhino.Runtime.Interop' Rhino.Runtime.CommonObject' Rhino.Runtime.FuzzyComparer' Rhino.DocObjects.Custom.UserData
Rhino.Runtime,RdkNotLoadedException,0,1,0,0,1,8,1,0,0,-1,0,0,,
Rhino.Runtime,Interop,0,19,0,0,15,430,43,0,0,-1,9,2,Rhino.Geometry.GeometryBase' Rhino.DocObjects.ViewportInfo' Rhino.Geometry.Arc' Rhino.Geometry.Brep' Rhino.Geometry.Surface' Rhino.Geometry.Mesh' Rhino.Geometry.Curve' Rhino.Runtime.HostUtils' Rhino.Geometry.Transform,Rhino.DocObjects.Material' Rhino.DocObjects.ObjectAttributes
Rhino.Runtime,MonoLoadResult,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Runtime,MonoHost,0,3,0,0,0,305,6,0,0,-1,0,0,,
Rhino.Runtime,DocumentCollectedException,0,1,0,0,1,9,1,0,0,-1,0,0,,
Rhino.Runtime,CommonObject,8,27,6,0,4,493,49,12,0,0.07,9,10,Rhino.DocObjects.Custom.UserDataList' Rhino.Geometry.PolyCurve' Rhino.Geometry.BrepLoop' Rhino.Geometry.Brep' Rhino.Runtime.InteropWrappers.StringHolder' Rhino.Geometry.MeshHolder' Rhino.Runtime.HostUtils' Rhino.Runtime.ConstCastHolder' Rhino.FileIO.SerializationOptions,Rhino.Runtime.ConstCastHolder' Rhino.Geometry.GeometryBase' Rhino.DocObjects.ViewportInfo' Rhino.DocObjects.DimensionStyle' Rhino.DocObjects.HatchPattern' Rhino.DocObjects.Layer' Rhino.DocObjects.Linetype' Rhino.DocObjects.Material' Rhino.DocObjects.Custom.UserData' Rhino.DocObjects.Custom.UserDataList
Rhino.Runtime,ConstCastHolder,1,1,0,1,1,8,1,0,0,0,1,1,Rhino.Runtime.CommonObject,Rhino.Runtime.CommonObject
Rhino.Runtime,DependencyAttribute,1,1,1,0,1,14,1,0,0,0,0,1,,Rhino.Runtime.AssemblyResolver
Rhino.Runtime,AssemblyResolver,5,5,0,0,2,271,40,0,0,0.4,2,1,Rhino.Runtime.FuzzyComparer' Rhino.Runtime.DependencyAttribute,Rhino.Runtime.HostUtils
Rhino.Runtime,FuzzyComparer,1,2,0,0,1,57,10,0,0,0,1,1,Rhino.Runtime.HostUtils,Rhino.Runtime.AssemblyResolver
Rhino,NamespaceDoc,0,0,0,0,0,10,0,0,0,-1,0,0,,
Rhino,IndexPair,2,1,2,0,1,34,1,0,0,0,0,3,,Rhino.Geometry.MeshTopologyEdgeList' Rhino.Render.MeshTopologyEdgeList' Rhino.Geometry.Collections.MeshTopologyEdgeList
Rhino,RhinoMath,6,12,0,5,12,213,26,0,0,0.75,1,31,Rhino.UnitSystem,Rhino.Geometry.Arc' Rhino.Geometry.BoundingBox' Rhino.Geometry.Circle' Rhino.Geometry.Cone' Rhino.Geometry.Curve' Rhino.Geometry.Cylinder' Rhino.Geometry.Ellipse' Rhino.Geometry.Point2f' Rhino.Geometry.Point3f' Rhino.Geometry.Vector2f' Rhino.Geometry.Vector3f' Rhino.Geometry.NurbsCurveKnotList' Rhino.Geometry.NurbsCurvePointList' Rhino.Geometry.NurbsSurfaceKnotList' Rhino.Geometry.Interval' Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Point4d' Rhino.Geometry.Vector2d' Rhino.Geometry.Vector3d' Rhino.Geometry.Quaternion' Rhino.Geometry.Rectangle3d' Rhino.Geometry.Sphere' Rhino.Geometry.Surface' Rhino.Geometry.Torus' Rhino.Geometry.Transform' Rhino.DocObjects.ViewportInfo' Rhino.Geometry.Collections.NurbsCurveKnotList' Rhino.Geometry.Collections.NurbsCurvePointList' Rhino.Geometry.Collections.NurbsSurfaceKnotList' Rhino.Geometry.Intersect.Intersection
Rhino,UnitSystem,0,0,0,0,0,81,0,0,0,-1,0,9,,Rhino.RhinoMath' Rhino.Geometry.RhinoMath' Rhino.Geometry.DetailView' Rhino.DocObjects.EarthAnchorPoint' Rhino.FileIO.EarthAnchorPoint' Rhino.Render.EarthAnchorPoint' Rhino.Display.EarthAnchorPoint' Geometry.RhinoMath' DocObjects.RhinoMath
Rhino,Continuity,0,0,0,0,0,105,0,0,0,-1,0,0,,
Rhino,MeshType,0,0,0,0,0,23,0,0,0,-1,0,0,,
Rhino,ActiveSpace,0,0,0,0,0,9,0,0,0,-1,0,0,,
Rhino,CoordinateSystem,0,0,0,0,0,20,0,0,0,-1,0,0,,
Rhino,ObjectMode,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino,ObjectColorSource,0,0,0,0,0,14,0,0,0,-1,0,0,,
Rhino,ObjectPlotColorSource,0,0,0,0,0,14,0,0,0,-1,0,0,,
Rhino,ObjectPlotWeightSource,0,0,0,0,0,12,0,0,0,-1,0,0,,
Rhino,ObjectLinetypeSource,0,0,0,0,0,12,0,0,0,-1,0,0,,
Rhino,ObjectMaterialSource,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino,DisplayMode,0,0,0,0,0,24,0,0,0,-1,0,0,,
Rhino,DistanceDisplayMode,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino,TextDisplayAlignment,0,0,0,0,0,19,0,0,0,-1,0,0,,
Rhino,ObjectType,0,0,0,0,0,111,0,0,0,-1,0,0,,
Rhino,ObjectDecoration,0,0,0,0,0,12,0,0,0,-1,0,0,,
Rhino,LightStyle,0,0,0,0,0,34,0,0,0,-1,0,0,,
Rhino,ComponentIndexType,0,0,0,0,0,83,0,0,0,-1,0,0,,
Rhino,ComponentIndex,2,1,3,0,1,80,1,0,0,0,1,0,Rhino.Geometry.ComponentIndexType,
Rhino,IEpsilonComparable,0,1,0,0,0,4,1,33,0,-1,0,0,,
Rhino,IEpsilonFComparable,0,1,0,0,0,4,1,4,0,-1,0,0,,
Rhino,SettingValue,4,36,3,2,34,463,85,0,0,0,2,1,Rhino.Geometry.Point3d' Rhino.PersistentSettingsEventArgs,Rhino.PersistentSettings
Rhino,PersistentSettingsEventArgs,0,1,1,0,0,12,1,1,0,-1,0,1,,Rhino.SettingValue
Rhino,PersistentSettingsEventArgs<T>,0,1,2,0,1,10,1,0,1,-1,0,0,,
Rhino,PersistentSettings,3,101,3,0,95,936,201,0,0,0.03,2,0,Rhino.SettingValue' Rhino.Geometry.Point3d,
Rhino.Geometry,NamespaceDoc,0,0,0,0,0,10,0,0,0,-1,0,0,,
Rhino.Geometry,TextJustification,0,0,0,0,0,68,0,0,0,-1,0,1,,Rhino.FileIO.File3dmObjectTable
Rhino.Geometry,AnnotationBase,0,5,6,0,0,146,5,6,1,-1,1,0,Rhino.Geometry.Point2d,
Rhino.Geometry,LinearDimension,5,6,8,0,3,154,6,0,2,0.83,2,1,Rhino.Geometry.Plane' Rhino.Geometry.Point2d,Rhino.FileIO.File3dmObjectTable
Rhino.Geometry,RadialDimension,0,4,1,0,2,59,4,0,2,-1,4,0,Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.Geometry.Circle' Rhino.Geometry.Plane,
Rhino.Geometry,AngularDimension,0,3,0,0,1,24,3,0,2,-1,1,0,Rhino.Geometry.Arc,
Rhino.Geometry,OrdinateDimension,0,2,0,0,0,14,2,0,2,-1,0,0,,
Rhino.Geometry,TextEntity,0,4,7,0,1,170,4,0,2,-1,0,0,,
Rhino.Geometry,Leader,0,2,0,0,0,14,2,0,2,-1,0,0,,
Rhino.Geometry,TextDot,0,4,4,0,1,103,4,0,1,-1,1,1,Rhino.Geometry.Point3d,Rhino.FileIO.File3dmObjectTable
Rhino.Geometry,Arc,3,20,20,0,20,616,27,0,1,0.55,9,10,Rhino.Geometry.Plane' Rhino.Geometry.Interval' Rhino.Geometry.Circle' Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.RhinoMath' Rhino.Geometry.BoundingBox' Rhino.Geometry.Transform' Rhino.Geometry.NurbsCurve,Rhino.Runtime.Interop' Rhino.Geometry.AngularDimension' Rhino.Geometry.ArcCurve' Rhino.Geometry.Circle' Rhino.Geometry.Curve' Rhino.Geometry.NurbsCurve' Rhino.Geometry.PolyCurve' Rhino.FileIO.File3dmObjectTable' Rhino.Collections.CurveList' Rhino.Geometry.Collections.NurbsCurve
Rhino.Geometry,ArcCurve,3,9,5,0,6,173,10,0,1,1,2,0,Rhino.Geometry.Arc' Rhino.Geometry.Circle,
Rhino.Geometry,Extrusion,0,21,12,0,18,470,25,0,1,-1,12,3,Rhino.Geometry.Curve' Rhino.Geometry.Cylinder' Rhino.Geometry.Brep' Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.Geometry.Transform' Rhino.Geometry.Plane' Rhino.Geometry.ComponentIndex' Rhino.Geometry.Surface' Rhino.Geometry.LineCurve' Rhino.Geometry.Mesh' Rhino.Geometry.MeshType,Rhino.Geometry.MeshHolder' Rhino.FileIO.File3dmObjectTable' Rhino.Geometry.Collections.MeshHolder
Rhino.Geometry,BezierCurve,1,22,3,0,18,306,29,0,0,0.14,7,1,Rhino.Geometry.Point3d' Rhino.Geometry.Point2d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Vector3d' Rhino.Geometry.GeometryBase' Rhino.Geometry.NurbsCurve' Rhino.Geometry.Point4d,Rhino.Runtime.HostUtils
Rhino.Geometry,BoundingBox,3,26,7,0,26,648,80,0,0,0.19,7,23,Rhino.Geometry.Point3d' Rhino.Geometry.Plane' Rhino.Geometry.Vector3d' Rhino.RhinoMath' Rhino.Geometry.Line' Rhino.Geometry.Transform' Rhino.Geometry.Brep,Rhino.Geometry.Arc' Rhino.Geometry.BezierCurve' Rhino.Geometry.Box' Rhino.Geometry.Brep' Rhino.Geometry.GeometryBase' Rhino.Geometry.Line' Rhino.Geometry.MeshFaceList' Rhino.Geometry.Plane' Rhino.Geometry.RTree' Rhino.Geometry.Surface' Rhino.Geometry.Transform' Rhino.DocObjects.ViewportInfo' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.File3dmObjectTable' Rhino.Render.MeshFaceList' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,Box,4,23,11,0,23,588,54,0,1,0.09,7,6,Rhino.Geometry.Plane' Rhino.Geometry.Interval' Rhino.Geometry.Point3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Transform' Rhino.Geometry.GeometryBase' Rhino.Geometry.Brep,Rhino.Geometry.Brep' Rhino.Geometry.GeometryBase' Rhino.Geometry.Line' Rhino.Geometry.Plane' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,PipeCapMode,0,0,0,0,0,9,0,0,0,-1,0,0,,
Rhino.Geometry,LoftType,0,0,0,0,0,30,0,0,0,-1,0,0,,
Rhino.Geometry,ExtrudeCornerType,0,0,0,0,0,13,0,0,0,-1,0,0,,
Rhino.Geometry,Brep,29,45,12,0,41,1794,55,0,1,0.73,22,45,Rhino.Geometry.Collections.BrepVertexList' Rhino.Geometry.Collections.BrepSurfaceList' Rhino.Geometry.Collections.BrepEdgeList' Rhino.Geometry.Collections.BrepTrimList' Rhino.Geometry.Collections.BrepLoopList' Rhino.Geometry.Collections.BrepFaceList' Rhino.Geometry.Collections.BrepCurveList' Rhino.Geometry.GeometryBase' Rhino.Geometry.Mesh' Rhino.Geometry.BoundingBox' Rhino.Geometry.Box' Rhino.Geometry.Point3d' Rhino.Geometry.Cylinder' Rhino.Geometry.Sphere' Rhino.Geometry.Cone' Rhino.Geometry.RevSurface' Rhino.Collections.CurveList' Rhino.Geometry.Curve' Rhino.Geometry.Surface' Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer' Rhino.Runtime.InteropWrappers.SimpleArrayPoint3d' Rhino.Runtime.InteropWrappers.StringHolder,Rhino.Runtime.Interop' Rhino.Runtime.CommonObject' Rhino.Geometry.Extrusion' Rhino.Geometry.BoundingBox' Rhino.Geometry.Box' Rhino.Geometry.BrepVertex' Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepTrim' Rhino.Geometry.BrepLoop' Rhino.Geometry.BrepFace' Rhino.Geometry.MeshHolder' Rhino.Geometry.SurfaceOfHolder' Rhino.Geometry.SurfaceHolder' Rhino.Geometry.CurveHolder' Rhino.Geometry.BrepVertexList' Rhino.Geometry.BrepFaceList' Rhino.Geometry.BrepSurfaceList' Rhino.Geometry.BrepCurveList' Rhino.Geometry.BrepEdgeList' Rhino.Geometry.BrepTrimList' Rhino.Geometry.BrepLoopList' Rhino.Geometry.Cone' Rhino.Geometry.Cylinder' Rhino.Geometry.GeometryBase' Rhino.Geometry.Sphere' Rhino.Geometry.Surface' Rhino.FileIO.File3dmObjectTable' Rhino.Runtime.InteropWrappers.SimpleArrayBrepPointer' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepVertex' Rhino.Geometry.Collections.BrepEdge' Rhino.Geometry.Collections.BrepTrim' Rhino.Geometry.Collections.BrepLoop' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.MeshHolder' Rhino.Geometry.Collections.SurfaceOfHolder' Rhino.Geometry.Collections.SurfaceHolder' Rhino.Geometry.Collections.CurveHolder' Rhino.Geometry.Collections.BrepVertexList' Rhino.Geometry.Collections.BrepFaceList' Rhino.Geometry.Collections.BrepSurfaceList' Rhino.Geometry.Collections.BrepCurveList' Rhino.Geometry.Collections.BrepEdgeList' Rhino.Geometry.Collections.BrepTrimList' Rhino.Geometry.Collections.BrepLoopList
Rhino.Geometry,PointFaceRelation,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Geometry,BrepSolidOrientation,0,0,0,0,0,19,0,0,0,-1,0,0,,
Rhino.Geometry,EdgeAdjacency,0,0,0,0,0,19,0,0,0,-1,0,0,,
Rhino.Geometry,BrepVertex,2,3,2,0,0,36,3,0,1,0,1,8,Rhino.Geometry.Brep,Rhino.Geometry.BrepVertexList' Rhino.Geometry.BrepFaceList' Rhino.Geometry.BrepEdgeList' Rhino.Geometry.BrepTrimList' Rhino.Geometry.Collections.BrepVertexList' Rhino.Geometry.Collections.BrepFaceList' Rhino.Geometry.Collections.BrepEdgeList' Rhino.Geometry.Collections.BrepTrimList
Rhino.Geometry,BrepEdge,2,5,7,0,3,179,6,0,1,0,3,6,Rhino.Geometry.Brep' Rhino.Runtime.InteropWrappers.SimpleArrayInt' Rhino.Geometry.Interval,Rhino.Geometry.BrepFaceList' Rhino.Geometry.BrepEdgeList' Rhino.Geometry.BrepTrimList' Rhino.Geometry.Collections.BrepFaceList' Rhino.Geometry.Collections.BrepEdgeList' Rhino.Geometry.Collections.BrepTrimList
Rhino.Geometry,BrepTrimType,0,0,0,0,0,43,0,0,0,-1,0,0,,
Rhino.Geometry,BrepTrim,5,7,7,0,4,214,8,0,1,0,2,2,Rhino.Geometry.Brep' Rhino.Geometry.Interval,Rhino.Geometry.BrepTrimList' Rhino.Geometry.Collections.BrepTrimList
Rhino.Geometry,BrepLoopType,0,0,0,0,0,29,0,0,0,-1,0,2,,Rhino.Geometry.BrepLoopList' Rhino.Geometry.Collections.BrepLoopList
Rhino.Geometry,BrepLoop,3,4,5,0,2,93,6,0,1,0,4,5,Rhino.Geometry.Brep' Rhino.Geometry.Collections.BrepTrimList' Rhino.Geometry.GeometryBase' Rhino.Geometry.Curve,Rhino.Runtime.CommonObject' Rhino.Geometry.BrepTrimList' Rhino.Geometry.BrepLoopList' Rhino.Geometry.Collections.BrepTrimList' Rhino.Geometry.Collections.BrepLoopList
Rhino.Geometry,BrepFace,3,12,6,0,9,394,17,0,1,0,11,12,Rhino.Geometry.Brep' Rhino.Geometry.Collections.BrepLoopList' Rhino.Geometry.SurfaceProxy' Rhino.Geometry.GeometryBase' Rhino.Geometry.Curve' Rhino.Geometry.Interval' Rhino.Geometry.Surface' Rhino.Geometry.Mesh' Rhino.Geometry.MeshType' Rhino.Geometry.MeshHolder' Rhino.Runtime.InteropWrappers.SimpleArrayInt,Rhino.Geometry.MeshHolder' Rhino.Geometry.SurfaceOfHolder' Rhino.Geometry.BrepVertexList' Rhino.Geometry.BrepFaceList' Rhino.Geometry.BrepTrimList' Rhino.Geometry.BrepLoopList' Rhino.Geometry.Collections.MeshHolder' Rhino.Geometry.Collections.SurfaceOfHolder' Rhino.Geometry.Collections.BrepVertexList' Rhino.Geometry.Collections.BrepFaceList' Rhino.Geometry.Collections.BrepTrimList' Rhino.Geometry.Collections.BrepLoopList
Rhino.Geometry,MeshHolder,3,4,0,0,4,71,6,0,0,0.5,4,6,Rhino.Geometry.BrepFace' Rhino.Geometry.Extrusion' Rhino.Geometry.MeshType' Rhino.Geometry.Brep,Rhino.Runtime.CommonObject' Rhino.Geometry.BrepFace' Rhino.Geometry.Mesh' Rhino.Render.Mesh' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.Mesh
Rhino.Geometry,SurfaceOfHolder,1,2,0,0,2,13,2,0,0,0,2,1,Rhino.Geometry.BrepFace' Rhino.Geometry.Brep,Rhino.Geometry.Surface
Rhino.Geometry,SurfaceHolder,2,2,0,0,2,15,2,0,0,0,1,1,Rhino.Geometry.Brep,Rhino.Geometry.Surface
Rhino.Geometry,CurveHolder,3,3,0,0,3,22,3,0,0,0,1,1,Rhino.Geometry.Brep,Rhino.Geometry.Curve
Rhino.Geometry,BrepVertexList,1,6,1,0,4,101,9,0,1,0.5,4,0,Rhino.Geometry.Brep' Rhino.Geometry.BrepVertex' Rhino.Geometry.Point3d' Rhino.Geometry.BrepFace,
Rhino.Geometry,BrepFaceList,2,14,1,0,12,331,19,0,1,0.21,6,0,Rhino.Geometry.Brep' Rhino.Geometry.GeometryBase' Rhino.Geometry.BrepFace' Rhino.Geometry.Surface' Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepVertex,
Rhino.Geometry,BrepSurfaceList,2,3,1,0,1,74,3,0,1,1,1,0,Rhino.Geometry.Brep,
Rhino.Geometry,BrepCurveList,3,4,1,0,2,87,4,0,1,0.75,2,0,Rhino.Geometry.Brep' Rhino.Geometry.Curve,
Rhino.Geometry,BrepEdgeList,2,8,1,0,6,171,10,0,1,0.75,4,0,Rhino.Geometry.Brep' Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepVertex' Rhino.Geometry.Interval,
Rhino.Geometry,BrepTrimList,3,10,1,0,7,186,10,0,1,0.3,7,0,Rhino.Geometry.Brep' Rhino.Geometry.BrepLoop' Rhino.Geometry.BrepTrim' Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepVertex' Rhino.Geometry.IsoStatus' Rhino.Geometry.BrepFace,
Rhino.Geometry,BrepLoopList,3,8,1,0,5,160,8,0,1,0.38,5,0,Rhino.Geometry.Brep' Rhino.Geometry.BrepFace' Rhino.Geometry.BrepLoop' Rhino.Geometry.BrepLoopType' Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer,
Rhino.Geometry,Circle,2,25,9,0,24,612,42,0,1,0.4,8,12,Rhino.Geometry.Plane' Rhino.RhinoMath' Rhino.Geometry.Curve' Rhino.Geometry.Point3d' Rhino.Geometry.Arc' Rhino.Geometry.Vector3d' Rhino.Geometry.Transform' Rhino.Geometry.NurbsCurve,Rhino.Geometry.RadialDimension' Rhino.Geometry.Arc' Rhino.Geometry.ArcCurve' Rhino.Geometry.Curve' Rhino.Geometry.Cylinder' Rhino.Geometry.NurbsCurve' Rhino.Geometry.Sphere' Rhino.Geometry.SurfaceCurvature' Rhino.FileIO.File3dmObjectTable' Rhino.Collections.CurveList' Rhino.Geometry.Collections.NurbsCurve' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,Cone,3,7,8,0,7,162,7,0,1,0.57,5,6,Rhino.Geometry.Plane' Rhino.Geometry.NurbsSurface' Rhino.Geometry.RevSurface' Rhino.Geometry.Brep' Rhino.RhinoMath,Rhino.Geometry.Brep' Rhino.Geometry.NurbsSurface' Rhino.Geometry.RevSurface' Rhino.Geometry.Surface' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.NurbsSurface
Rhino.Geometry,BlendContinuity,0,0,0,0,0,9,0,0,0,-1,0,0,,
Rhino.Geometry,CurveOffsetCornerStyle,0,0,0,0,0,23,0,0,0,-1,0,0,,
Rhino.Geometry,CurveKnotStyle,0,0,0,0,0,27,0,0,0,-1,0,0,,
Rhino.Geometry,CurveOrientation,0,0,0,0,0,15,0,0,0,-1,0,1,,Rhino.Geometry.Curve
Rhino.Geometry,PointContainment,0,0,0,0,0,19,0,0,0,-1,0,1,,Rhino.Geometry.Rectangle3d
Rhino.Geometry,RegionContainment,0,0,0,0,0,19,0,0,0,-1,0,0,,
Rhino.Geometry,CurveExtensionStyle,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Geometry,CurveSimplifyOptions,0,0,0,0,0,39,0,0,0,-1,0,0,,
Rhino.Geometry,CurveEnd,0,0,0,0,0,20,0,0,0,-1,0,2,,Rhino.Geometry.NurbsCurveKnotList' Rhino.Geometry.Collections.NurbsCurveKnotList
Rhino.Geometry,CurveEvaluationSide,0,0,0,0,0,15,0,0,0,-1,0,1,,Rhino.Geometry.Curve
Rhino.Geometry,Curve,11,69,10,0,59,3412,94,7,1,0.64,22,20,Rhino.Geometry.Point3d' Rhino.Collections.Point3dList' Rhino.Geometry.PolylineCurve' Rhino.Geometry.GeometryBase' Rhino.Geometry.LineCurve' Rhino.Geometry.NurbsCurve' Rhino.Geometry.CurveHolder' Rhino.Geometry.PolyCurve' Rhino.RhinoMath' Rhino.Runtime.InteropWrappers.SimpleArrayPoint3d' Rhino.Geometry.Polyline' Rhino.Runtime.InteropWrappers.SimpleArrayDouble' Rhino.Geometry.Arc' Rhino.Geometry.Plane' Rhino.Geometry.Circle' Rhino.Geometry.Ellipse' Rhino.Geometry.CurveOrientation' Rhino.Geometry.Vector3d' Rhino.Geometry.Transform' Rhino.Geometry.CurveEvaluationSide' Rhino.Geometry.Continuity' Rhino.Geometry.Interval,Rhino.Runtime.Interop' Rhino.Geometry.Extrusion' Rhino.Geometry.Brep' Rhino.Geometry.BrepLoop' Rhino.Geometry.BrepFace' Rhino.Geometry.BrepCurveList' Rhino.Geometry.Circle' Rhino.Geometry.NurbsSurface' Rhino.Geometry.PolyCurve' Rhino.Geometry.RevSurface' Rhino.Geometry.SumSurface' Rhino.Geometry.Surface' Rhino.FileIO.File3dmObjectTable' Rhino.Collections.CurveList' Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepLoop' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.BrepCurveList' Rhino.Geometry.Collections.NurbsSurface
Rhino.Geometry,CurveProxy,0,2,1,0,0,26,2,4,2,-1,0,0,,
Rhino.Geometry,Cylinder,3,8,8,0,8,269,10,0,1,0.5,9,9,Rhino.Geometry.Circle' Rhino.Geometry.Plane' Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.Geometry.Line' Rhino.Geometry.Brep' Rhino.Geometry.NurbsSurface' Rhino.Geometry.RevSurface' Rhino.RhinoMath,Rhino.Geometry.Extrusion' Rhino.Geometry.Brep' Rhino.Geometry.NurbsSurface' Rhino.Geometry.RevSurface' Rhino.Geometry.Surface' Rhino.Render.TextureMapping' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.NurbsSurface' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,IndexPair,2,1,2,0,1,34,1,0,0,0,0,0,,
Rhino.Geometry,RhinoMath,6,12,0,5,12,213,26,0,0,0.92,1,0,Rhino.UnitSystem,
Rhino.Geometry,UnitSystem,0,0,0,0,0,81,0,0,0,-1,0,0,,
Rhino.Geometry,Continuity,0,0,0,0,0,105,0,0,0,-1,0,2,,Rhino.Geometry.Curve' Rhino.Geometry.Surface
Rhino.Geometry,MeshType,0,0,0,0,0,23,0,0,0,-1,0,5,,Rhino.Geometry.Extrusion' Rhino.Geometry.BrepFace' Rhino.Geometry.MeshHolder' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.MeshHolder
Rhino.Geometry,ActiveSpace,0,0,0,0,0,9,0,0,0,-1,0,0,,
Rhino.Geometry,CoordinateSystem,0,0,0,0,0,20,0,0,0,-1,0,0,,
Rhino.Geometry,ObjectMode,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Geometry,ObjectColorSource,0,0,0,0,0,14,0,0,0,-1,0,0,,
Rhino.Geometry,ObjectPlotColorSource,0,0,0,0,0,14,0,0,0,-1,0,0,,
Rhino.Geometry,ObjectPlotWeightSource,0,0,0,0,0,12,0,0,0,-1,0,0,,
Rhino.Geometry,ObjectLinetypeSource,0,0,0,0,0,12,0,0,0,-1,0,0,,
Rhino.Geometry,ObjectMaterialSource,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Geometry,DisplayMode,0,0,0,0,0,24,0,0,0,-1,0,0,,
Rhino.Geometry,DistanceDisplayMode,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Geometry,TextDisplayAlignment,0,0,0,0,0,19,0,0,0,-1,0,0,,
Rhino.Geometry,ObjectType,0,0,0,0,0,111,0,0,0,-1,0,0,,
Rhino.Geometry,ObjectDecoration,0,0,0,0,0,12,0,0,0,-1,0,0,,
Rhino.Geometry,LightStyle,0,0,0,0,0,34,0,0,0,-1,0,0,,
Rhino.Geometry,ComponentIndexType,0,0,0,0,0,83,0,0,0,-1,0,4,,Rhino.ComponentIndex' Rhino.Geometry.ComponentIndex' Geometry.ComponentIndex' DocObjects.ComponentIndex
Rhino.Geometry,ComponentIndex,2,1,3,0,1,80,1,0,0,0,1,3,Rhino.Geometry.ComponentIndexType,Rhino.Geometry.Extrusion' Rhino.Geometry.GeometryBase' Rhino.Runtime.InteropWrappers.INTERNAL_ComponentIndexArray
Rhino.Geometry,DetailView,3,4,4,0,1,121,5,0,1,1,1,0,Rhino.UnitSystem,
Rhino.Geometry,Ellipse,3,4,3,0,4,88,4,0,1,0.5,4,5,Rhino.Geometry.Plane' Rhino.Geometry.Point3d' Rhino.Geometry.NurbsCurve' Rhino.RhinoMath,Rhino.Geometry.Curve' Rhino.Geometry.NurbsCurve' Rhino.FileIO.File3dmObjectTable' Rhino.Collections.CurveList' Rhino.Geometry.Collections.NurbsCurve
Rhino.Geometry,Point2f,2,9,4,0,8,209,14,0,1,0.33,1,3,Rhino.RhinoMath,Rhino.Geometry.MeshTextureCoordinateList' Rhino.Render.MeshTextureCoordinateList' Rhino.Geometry.Collections.MeshTextureCoordinateList
Rhino.Geometry,Point3f,3,11,6,0,10,274,20,0,1,0.27,4,18,Rhino.RhinoMath' Rhino.Geometry.Vector3d' Rhino.Geometry.Transform' Rhino.Geometry.Vector3f,Rhino.Geometry.Vector3f' Rhino.Geometry.MeshVertexList' Rhino.Geometry.MeshFaceList' Rhino.Geometry.MeshTextureCoordinateList' Rhino.Geometry.Point3d' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.File3dmObjectTable' Rhino.Render.MeshVertexList' Rhino.Render.MeshFaceList' Rhino.Render.MeshTextureCoordinateList' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Collections.MeshTextureCoordinateList
Rhino.Geometry,Vector2f,2,7,2,0,6,159,12,0,1,0.43,1,0,Rhino.RhinoMath,
Rhino.Geometry,Vector3f,3,18,9,0,16,427,32,0,1,0.39,3,15,Rhino.RhinoMath' Rhino.Geometry.Transform' Rhino.Geometry.Point3f,Rhino.Geometry.Point3f' Rhino.Geometry.MeshVertexNormalList' Rhino.Geometry.MeshFaceNormalList' Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Render.MeshVertexNormalList' Rhino.Render.MeshFaceNormalList' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Geometry.Collections.MeshVertexNormalList' Rhino.Geometry.Collections.MeshFaceNormalList
Rhino.Geometry,GeometryBase,42,27,5,0,17,636,40,22,1,0.67,10,31,Rhino.FileIO.File3dmObject' Rhino.Runtime.CommonObject' Rhino.Geometry.Brep' Rhino.Geometry.Transform' Rhino.Geometry.Vector3d' Rhino.Geometry.Point3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Plane' Rhino.Geometry.Box' Rhino.Geometry.ComponentIndex,Rhino.Runtime.HostUtils' Rhino.Runtime.Interop' Rhino.Geometry.BezierCurve' Rhino.Geometry.Box' Rhino.Geometry.Brep' Rhino.Geometry.BrepLoop' Rhino.Geometry.BrepFace' Rhino.Geometry.BrepFaceList' Rhino.Geometry.Curve' Rhino.Geometry.InstanceDefinitionGeometry' Rhino.Geometry.Mesh' Rhino.Geometry.PolyCurve' Rhino.Geometry.Surface' Rhino.Geometry.SpaceMorph' Rhino.DocObjects.ViewportInfo' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.File3dmObject' Rhino.Render.Mesh' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Runtime.InteropWrappers.SimpleArraySurfacePointer' Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer' Rhino.Runtime.InteropWrappers.SimpleArrayGeometryPointer' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepLoop' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.BrepFaceList' Rhino.Geometry.Collections.Mesh
Rhino.Geometry,UnknownGeometry,0,1,0,0,1,7,1,0,2,-1,0,0,,
Rhino.Geometry,Hatch,0,4,3,0,1,186,4,0,2,-1,1,1,Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer,Rhino.FileIO.File3dmObjectTable
Rhino.Geometry,InstanceDefinitionGeometry,3,7,3,0,2,121,9,0,2,0.71,3,1,Rhino.FileIO.File3dm' Rhino.Geometry.GeometryBase' Rhino.Runtime.InteropWrappers.SimpleArrayGuid,Rhino.FileIO.File3dmInstanceDefinitionTable
Rhino.Geometry,InstanceReferenceGeometry,0,3,2,0,1,45,3,0,2,-1,1,0,Rhino.Geometry.Transform,
Rhino.Geometry,Light,17,15,26,0,4,490,15,0,2,1,1,0,Rhino.Geometry.Vector3d,
Rhino.Geometry,Line,2,27,14,0,26,555,44,0,1,0.48,7,23,Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.Geometry.Transform' Rhino.Geometry.NurbsCurve' Rhino.Geometry.BoundingBox' Rhino.Geometry.Box' Rhino.Geometry.Plane,Rhino.Geometry.BoundingBox' Rhino.Geometry.Cylinder' Rhino.Geometry.LineCurve' Rhino.Geometry.MeshTopologyEdgeList' Rhino.Geometry.NurbsCurve' Rhino.Geometry.PolyCurve' Rhino.Geometry.Polyline' Rhino.Geometry.Rectangle3d' Rhino.Geometry.RevSurface' Rhino.DocObjects.ViewportInfo' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.File3dmObjectTable' Rhino.Render.MeshTopologyEdgeList' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Collections.CurveList' Rhino.Runtime.InteropWrappers.SimpleArrayLine' Rhino.Geometry.Collections.MeshTopologyEdgeList' Rhino.Geometry.Collections.NurbsCurve' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,LineCurve,0,9,1,0,6,115,10,0,2,-1,3,2,Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Line,Rhino.Geometry.Extrusion' Rhino.Geometry.Curve
Rhino.Geometry,Matrix,7,19,8,0,17,405,32,0,0,0.16,2,0,Rhino.Geometry.Transform' Rhino.Geometry.Point3d,
Rhino.Geometry,CachedTextureCoordinates,0,30,8,0,20,509,44,0,1,-1,4,0,Rhino.Render.CachedTextureCoordinates' Rhino.Geometry.Mesh' Rhino.Geometry.Point3d' Rhino.Render.CachedTextureCoordinatesEnumerator,
Rhino.Geometry,CachedTextureCoordinatesEnumerator,6,8,4,0,6,79,8,0,0,0.38,0,0,,
Rhino.Geometry,MappingTag,0,0,8,0,0,41,0,0,0,-1,0,0,,
Rhino.Geometry,MeshingParameterStyle,0,0,0,0,0,25,0,0,0,-1,0,0,,
Rhino.Geometry,MeshingParameters,28,24,38,0,4,715,26,0,0,0,0,6,,Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader
Rhino.Geometry,MeshPart,12,2,12,0,0,59,2,0,0,0,0,3,,Rhino.Geometry.Mesh' Rhino.Render.Mesh' Rhino.Geometry.Collections.Mesh
Rhino.Geometry,Mesh,112,50,24,0,34,2835,74,0,2,0.86,16,40,Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshTopologyVertexList' Rhino.Geometry.Collections.MeshTopologyEdgeList' Rhino.Geometry.Collections.MeshVertexNormalList' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Collections.MeshFaceNormalList' Rhino.Geometry.Collections.MeshVertexColorList' Rhino.Geometry.Collections.MeshTextureCoordinateList' Rhino.Geometry.MeshHolder' Rhino.Geometry.GeometryBase' Rhino.Geometry.Surface' Rhino.Render.TextureMapping' Rhino.Geometry.Transform' Rhino.Render.CachedTextureCoordinates' Rhino.Geometry.Point3d' Rhino.Geometry.MeshPart,Rhino.Runtime.Interop' Rhino.Geometry.Extrusion' Rhino.Geometry.Brep' Rhino.Geometry.BrepFace' Rhino.Geometry.CachedTextureCoordinates' Rhino.Geometry.MeshVertexList' Rhino.Geometry.MeshTopologyVertexList' Rhino.Geometry.MeshTopologyEdgeList' Rhino.Geometry.MeshVertexNormalList' Rhino.Geometry.MeshFaceList' Rhino.Geometry.MeshFaceNormalList' Rhino.Geometry.MeshVertexColorList' Rhino.Geometry.MeshTextureCoordinateList' Rhino.Geometry.MeshPoint' Rhino.Geometry.RTree' Rhino.FileIO.File3dmObjectTable' Rhino.Render.CachedTextureCoordinates' Rhino.Render.Mesh' Rhino.Render.MeshVertexList' Rhino.Render.MeshTopologyVertexList' Rhino.Render.MeshTopologyEdgeList' Rhino.Render.MeshVertexNormalList' Rhino.Render.MeshFaceList' Rhino.Render.MeshFaceNormalList' Rhino.Render.MeshVertexColorList' Rhino.Render.MeshTextureCoordinateList' Rhino.Runtime.InteropWrappers.SimpleArrayMeshPointer' Rhino.Runtime.InteropWrappers.MeshPoint' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.CachedTextureCoordinates' Rhino.Geometry.Collections.Mesh' Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshTopologyVertexList' Rhino.Geometry.Collections.MeshTopologyEdgeList' Rhino.Geometry.Collections.MeshVertexNormalList' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Collections.MeshFaceNormalList' Rhino.Geometry.Collections.MeshVertexColorList' Rhino.Geometry.Collections.MeshTextureCoordinateList
Rhino.Geometry,MeshVertexList,2,58,2,0,54,1009,110,0,1,0.33,6,0,Rhino.Geometry.Mesh' Rhino.Geometry.Point3f' Rhino.Geometry.Point3d' Rhino.Runtime.InteropWrappers.SimpleArrayInt' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.MeshFace,
Rhino.Geometry,MeshTopologyVertexList,2,24,2,0,20,421,40,0,1,0.29,2,0,Rhino.Geometry.Mesh' Rhino.Runtime.InteropWrappers.SimpleArrayInt,
Rhino.Geometry,MeshTopologyEdgeList,2,24,2,0,22,419,40,0,0,0,4,0,Rhino.Geometry.Mesh' Rhino.IndexPair' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Line,
Rhino.Geometry,MeshVertexNormalList,2,36,2,0,30,483,40,0,1,0.64,3,0,Rhino.Geometry.Mesh' Rhino.Geometry.Vector3f' Rhino.Geometry.Vector3d,
Rhino.Geometry,MeshFaceList,2,52,6,0,48,963,86,0,1,0.33,6,0,Rhino.Geometry.Mesh' Rhino.Geometry.MeshFace' Rhino.Geometry.Point3f' Rhino.Geometry.BoundingBox' Rhino.Geometry.Point3d' Rhino.Geometry.Collections.MeshTopologyEdgeList,
Rhino.Geometry,MeshFaceNormalList,2,28,2,0,24,375,28,0,1,0.68,3,0,Rhino.Geometry.Mesh' Rhino.Geometry.Vector3d' Rhino.Geometry.Vector3f,
Rhino.Geometry,MeshVertexColorList,2,26,4,0,20,461,34,0,1,0.65,3,0,Rhino.Geometry.Mesh' Rhino.Geometry.MeshFace' Rhino.Geometry.Collections.MeshVertexList,
Rhino.Geometry,MeshTextureCoordinateList,2,38,2,0,32,501,42,0,1,0.61,5,0,Rhino.Geometry.Mesh' Rhino.Geometry.Point2f' Rhino.Geometry.Point3d' Rhino.Geometry.Point3f' Rhino.Render.TextureMapping,
Rhino.Geometry,MeshFace,8,14,16,0,14,421,44,0,0,0,0,11,,Rhino.Geometry.MeshVertexList' Rhino.Geometry.MeshFaceList' Rhino.Geometry.MeshVertexColorList' Rhino.Render.MeshVertexList' Rhino.Render.MeshFaceList' Rhino.Render.MeshVertexColorList' Rhino.Render.MeshFace' Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Collections.MeshVertexColorList' Rhino.Geometry.Collections.MeshFace
Rhino.Geometry,NurbsCurve,16,23,5,0,17,530,42,0,2,0.78,9,16,Rhino.Geometry.Collections.NurbsCurveKnotList' Rhino.Geometry.Collections.NurbsCurvePointList' Rhino.Geometry.Line' Rhino.Geometry.Arc' Rhino.Geometry.Circle' Rhino.Geometry.Transform' Rhino.Geometry.Ellipse' Rhino.Geometry.Point3d' Rhino.Collections.Point3dList,Rhino.Geometry.Arc' Rhino.Geometry.BezierCurve' Rhino.Geometry.Circle' Rhino.Geometry.Curve' Rhino.Geometry.Ellipse' Rhino.Geometry.Line' Rhino.Geometry.NurbsCurveKnotList' Rhino.Geometry.NurbsCurvePointList' Rhino.Geometry.MorphControl' Rhino.Geometry.Polyline' Rhino.Geometry.Rectangle3d' Rhino.Collections.CurveList' Rhino.Geometry.Collections.NurbsCurve' Rhino.Geometry.Collections.NurbsCurveKnotList' Rhino.Geometry.Collections.NurbsCurvePointList' Rhino.Geometry.Collections.MorphControl
Rhino.Geometry,ControlPoint,1,6,3,0,6,118,6,0,1,0,2,5,Rhino.Geometry.Point4d' Rhino.Geometry.Point3d,Rhino.Geometry.NurbsCurvePointList' Rhino.Geometry.NurbsSurfacePointList' Rhino.Geometry.Collections.ControlPoint' Rhino.Geometry.Collections.NurbsCurvePointList' Rhino.Geometry.Collections.NurbsSurfacePointList
Rhino.Geometry,NurbsCurveKnotList,1,12,3,0,9,197,19,0,1,0.42,4,0,Rhino.Geometry.NurbsCurve' Rhino.Geometry.CurveEnd' Rhino.Geometry.Collections.NurbsCurveKnotList' Rhino.RhinoMath,
Rhino.Geometry,NurbsCurvePointList,1,12,2,0,9,198,20,0,1,0.5,7,0,Rhino.Geometry.NurbsCurve' Rhino.Geometry.Polyline' Rhino.Geometry.ControlPoint' Rhino.Geometry.Point4d' Rhino.Geometry.Point3d' Rhino.Geometry.Collections.NurbsCurvePointList' Rhino.RhinoMath,
Rhino.Geometry,NurbsSurface,13,17,6,0,13,514,33,0,1,1,7,10,Rhino.Geometry.Collections.NurbsSurfaceKnotList' Rhino.Geometry.Collections.NurbsSurfacePointList' Rhino.Geometry.Cone' Rhino.Geometry.Cylinder' Rhino.Geometry.Sphere' Rhino.Geometry.Torus' Rhino.Geometry.Curve,Rhino.Geometry.Cone' Rhino.Geometry.Cylinder' Rhino.Geometry.NurbsSurfacePointList' Rhino.Geometry.NurbsSurfaceKnotList' Rhino.Geometry.Sphere' Rhino.Geometry.Surface' Rhino.Geometry.Torus' Rhino.Geometry.Collections.NurbsSurface' Rhino.Geometry.Collections.NurbsSurfacePointList' Rhino.Geometry.Collections.NurbsSurfaceKnotList
Rhino.Geometry,MorphControl,0,3,3,0,1,113,3,0,2,-1,1,0,Rhino.Geometry.NurbsCurve,
Rhino.Geometry,NurbsSurfacePointList,1,9,2,0,6,220,29,0,1,0.56,7,0,Rhino.Geometry.NurbsSurface' Rhino.Geometry.Point2d' Rhino.Geometry.Point4d' Rhino.Geometry.ControlPoint' Rhino.Geometry.Point3d' Rhino.Geometry.Collections.NurbsSrfEnum' Rhino.Geometry.Collections.NurbsSurfacePointList,
Rhino.Geometry,NurbsSrfEnum,5,4,3,0,4,74,5,0,0,0.75,1,0,Rhino.Geometry.Collections.NurbsSurfacePointList,
Rhino.Geometry,NurbsSurfaceKnotList,2,11,3,0,8,174,17,0,1,0.36,3,0,Rhino.Geometry.NurbsSurface' Rhino.Geometry.Collections.NurbsSurfaceKnotList' Rhino.RhinoMath,
Rhino.Geometry,PlaneFitResult,0,0,0,0,0,16,0,0,0,-1,0,0,,
Rhino.Geometry,Plane,4,28,13,0,27,611,39,0,1,0.43,6,38,Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.Geometry.Interval' Rhino.Geometry.BoundingBox' Rhino.Geometry.Box' Rhino.Geometry.Transform,Rhino.Geometry.LinearDimension' Rhino.Geometry.RadialDimension' Rhino.Geometry.Arc' Rhino.Geometry.Extrusion' Rhino.Geometry.BoundingBox' Rhino.Geometry.Box' Rhino.Geometry.Circle' Rhino.Geometry.Cone' Rhino.Geometry.Curve' Rhino.Geometry.Cylinder' Rhino.Geometry.Ellipse' Rhino.Geometry.GeometryBase' Rhino.Geometry.Line' Rhino.Geometry.PlaneSurface' Rhino.Geometry.Vector3d' Rhino.Geometry.Rectangle3d' Rhino.Geometry.Sphere' Rhino.Geometry.Surface' Rhino.Geometry.Torus' Rhino.Geometry.Transform' Rhino.DocObjects.ConstructionPlane' Rhino.DocObjects.EarthAnchorPoint' Rhino.DocObjects.ViewportInfo' Rhino.FileIO.ConstructionPlane' Rhino.FileIO.EarthAnchorPoint' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.File3dmObjectTable' Rhino.Render.ConstructionPlane' Rhino.Render.EarthAnchorPoint' Rhino.Render.TextureMapping' Rhino.Display.ConstructionPlane' Rhino.Display.EarthAnchorPoint' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,PlaneSurface,0,4,0,0,1,74,4,1,1,-1,2,1,Rhino.Geometry.Plane' Rhino.Geometry.Interval,Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,ClippingPlaneSurface,0,4,1,0,1,54,5,0,2,-1,0,0,,
Rhino.Geometry,MeshPointDataStruct,13,0,0,13,0,72,0,0,0,-1,0,0,,
Rhino.Geometry,MeshPoint,3,1,8,0,0,105,1,0,0,0,2,0,Rhino.Geometry.Mesh' Rhino.Runtime.InteropWrappers.MeshPointDataStruct,
Rhino.Geometry,Interval,2,25,11,0,22,520,42,0,1,0.2,1,26,Rhino.RhinoMath,Rhino.Geometry.Arc' Rhino.Geometry.Box' Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepTrim' Rhino.Geometry.BrepFace' Rhino.Geometry.BrepEdgeList' Rhino.Geometry.Curve' Rhino.Geometry.Plane' Rhino.Geometry.PlaneSurface' Rhino.Geometry.PolyCurve' Rhino.Geometry.Polyline' Rhino.Geometry.Rectangle3d' Rhino.Geometry.Surface' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Render.TextureMapping' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Runtime.InteropWrappers.SimpleArrayInterval' Rhino.Geometry.Collections.BrepEdge' Rhino.Geometry.Collections.BrepTrim' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.BrepEdgeList' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,Point2d,2,23,7,0,20,517,30,0,1,0.57,4,15,Rhino.Geometry.Vector2d' Rhino.Geometry.Point3d' Rhino.RhinoMath' Rhino.Geometry.Transform,Rhino.Geometry.AnnotationBase' Rhino.Geometry.LinearDimension' Rhino.Geometry.BezierCurve' Rhino.Geometry.LineCurve' Rhino.Geometry.NurbsSurfacePointList' Rhino.Geometry.RTree' Rhino.Geometry.SurfaceCurvature' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Runtime.InteropWrappers.SimpleArrayPoint2d' Rhino.Geometry.Collections.NurbsSurfacePointList
Rhino.Geometry,Point3d,3,27,8,0,24,777,42,0,1,0.11,7,71,Rhino.Geometry.Vector3d' Rhino.Geometry.Point3f' Rhino.Geometry.Point4d' Rhino.Geometry.Vector3f' Rhino.RhinoMath' Rhino.Geometry.Transform' Rhino.Collections.Point3dList,Rhino.SettingValue' Rhino.PersistentSettings' Rhino.Geometry.RadialDimension' Rhino.Geometry.TextDot' Rhino.Geometry.Arc' Rhino.Geometry.Extrusion' Rhino.Geometry.BezierCurve' Rhino.Geometry.BoundingBox' Rhino.Geometry.Box' Rhino.Geometry.Brep' Rhino.Geometry.BrepVertexList' Rhino.Geometry.Circle' Rhino.Geometry.Curve' Rhino.Geometry.Cylinder' Rhino.Geometry.Ellipse' Rhino.Geometry.GeometryBase' Rhino.Geometry.Line' Rhino.Geometry.LineCurve' Rhino.Geometry.Matrix' Rhino.Geometry.CachedTextureCoordinates' Rhino.Geometry.Mesh' Rhino.Geometry.MeshVertexList' Rhino.Geometry.MeshFaceList' Rhino.Geometry.MeshTextureCoordinateList' Rhino.Geometry.NurbsCurve' Rhino.Geometry.ControlPoint' Rhino.Geometry.NurbsCurvePointList' Rhino.Geometry.NurbsSurfacePointList' Rhino.Geometry.Plane' Rhino.Geometry.Point2d' Rhino.Geometry.Point4d' Rhino.Geometry.Vector3d' Rhino.Geometry.Ray3d' Rhino.Geometry.PointCloud' Rhino.Geometry.Point' Rhino.Geometry.Polyline' Rhino.Geometry.PolylineCurve' Rhino.Geometry.Rectangle3d' Rhino.Geometry.RTree' Rhino.Geometry.Sphere' Rhino.Geometry.SurfaceCurvature' Rhino.Geometry.Surface' Rhino.Geometry.Transform' Rhino.Geometry.SpaceMorph' Rhino.DocObjects.ViewportInfo' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.File3dmObjectTable' Rhino.Render.CachedTextureCoordinates' Rhino.Render.Mesh' Rhino.Render.MeshVertexList' Rhino.Render.MeshFaceList' Rhino.Render.MeshTextureCoordinateList' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Collections.Point3dList' Rhino.Runtime.InteropWrappers.SimpleArrayPoint3d' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepVertexList' Rhino.Geometry.Collections.CachedTextureCoordinates' Rhino.Geometry.Collections.Mesh' Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Collections.MeshTextureCoordinateList' Rhino.Geometry.Collections.NurbsCurve' Rhino.Geometry.Collections.ControlPoint' Rhino.Geometry.Collections.NurbsCurvePointList' Rhino.Geometry.Collections.NurbsSurfacePointList' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,Point4d,4,11,5,0,9,279,11,0,1,0.55,2,14,Rhino.Geometry.Point3d' Rhino.RhinoMath,Rhino.Geometry.BezierCurve' Rhino.Geometry.ControlPoint' Rhino.Geometry.NurbsCurvePointList' Rhino.Geometry.NurbsSurfacePointList' Rhino.Geometry.Point3d' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Geometry.Collections.ControlPoint' Rhino.Geometry.Collections.NurbsCurvePointList' Rhino.Geometry.Collections.NurbsSurfacePointList
Rhino.Geometry,Vector2d,2,11,6,0,8,226,16,0,1,0.45,1,7,Rhino.RhinoMath,Rhino.Geometry.Point2d' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader
Rhino.Geometry,Vector3d,3,35,15,0,31,836,58,0,1,0.2,5,37,Rhino.Geometry.Point3d' Rhino.Geometry.Vector3f' Rhino.RhinoMath' Rhino.Geometry.Plane' Rhino.Geometry.Transform,Rhino.Geometry.RadialDimension' Rhino.Geometry.Arc' Rhino.Geometry.Extrusion' Rhino.Geometry.BezierCurve' Rhino.Geometry.BoundingBox' Rhino.Geometry.Circle' Rhino.Geometry.Curve' Rhino.Geometry.Cylinder' Rhino.Geometry.Point3f' Rhino.Geometry.GeometryBase' Rhino.Geometry.Light' Rhino.Geometry.Line' Rhino.Geometry.MeshVertexNormalList' Rhino.Geometry.MeshFaceNormalList' Rhino.Geometry.Plane' Rhino.Geometry.Point3d' Rhino.Geometry.Ray3d' Rhino.Geometry.PointCloud' Rhino.Geometry.Polyline' Rhino.Geometry.Quaternion' Rhino.Geometry.Rectangle3d' Rhino.Geometry.Sphere' Rhino.Geometry.SurfaceCurvature' Rhino.Geometry.Surface' Rhino.Geometry.Transform' Rhino.DocObjects.ViewportInfo' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Render.MeshVertexNormalList' Rhino.Render.MeshFaceNormalList' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Geometry.Collections.MeshVertexNormalList' Rhino.Geometry.Collections.MeshFaceNormalList' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,Ray3d,2,8,2,0,6,116,9,0,1,0.38,2,6,Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d,Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader
Rhino.Geometry,PointCloudItem,2,1,8,0,0,143,1,0,0,0,1,1,Rhino.Geometry.PointCloud,Rhino.Geometry.PointCloud
Rhino.Geometry,PointCloud,7,28,5,0,24,474,52,0,2,0.86,5,4,Rhino.Collections.Point3dList' Rhino.Geometry.Point3d' Rhino.Geometry.PointCloudItem' Rhino.Geometry.Vector3d' Rhino.Geometry.PointCloudItemEnumerator,Rhino.Geometry.PointCloudItem' Rhino.Geometry.PointCloudItemEnumerator' Rhino.Geometry.RTree' Rhino.FileIO.File3dmObjectTable
Rhino.Geometry,PointCloudItemEnumerator,3,4,2,0,4,61,5,0,0,0.5,1,1,Rhino.Geometry.PointCloud,Rhino.Geometry.PointCloud
Rhino.Geometry,Point,0,4,1,0,1,47,4,2,2,-1,1,0,Rhino.Geometry.Point3d,
Rhino.Geometry,Point3dGrid,0,4,0,0,2,35,4,0,2,-1,0,0,,
Rhino.Geometry,PolyCurve,2,18,3,0,14,336,24,0,2,0.94,6,2,Rhino.Geometry.GeometryBase' Rhino.Geometry.Curve' Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer' Rhino.Geometry.Line' Rhino.Geometry.Arc' Rhino.Geometry.Interval,Rhino.Runtime.CommonObject' Rhino.Geometry.Curve
Rhino.Geometry,Polyline,0,23,4,0,18,638,94,0,1,-1,7,5,Rhino.Runtime.InteropWrappers.SimpleArrayPoint3d' Rhino.Geometry.Point3d' Rhino.Geometry.Line' Rhino.Geometry.Vector3d' Rhino.Geometry.Interval' Rhino.Geometry.PolylineCurve' Rhino.Geometry.NurbsCurve,Rhino.Geometry.Curve' Rhino.Geometry.NurbsCurvePointList' Rhino.Geometry.Rectangle3d' Rhino.Geometry.RevSurface' Rhino.Geometry.Collections.NurbsCurvePointList
Rhino.Geometry,PolylineCurve,0,9,1,0,5,111,11,0,2,-1,2,2,Rhino.Collections.Point3dList' Rhino.Geometry.Point3d,Rhino.Geometry.Curve' Rhino.Geometry.Polyline
Rhino.Geometry,Quaternion,4,12,18,0,12,563,13,0,1,0.25,3,0,Rhino.RhinoMath' Rhino.Geometry.Transform' Rhino.Geometry.Vector3d,
Rhino.Geometry,Rectangle3d,3,20,11,0,19,469,58,0,1,0,11,0,Rhino.Geometry.Plane' Rhino.Geometry.Interval' Rhino.Collections.Point3dList' Rhino.Geometry.Vector3d' Rhino.Geometry.Point3d' Rhino.RhinoMath' Rhino.Geometry.Line' Rhino.Geometry.PointContainment' Rhino.Geometry.Transform' Rhino.Geometry.Polyline' Rhino.Geometry.NurbsCurve,
Rhino.Geometry,RevSurface,0,13,0,0,10,158,18,0,1,-1,7,6,Rhino.Geometry.Curve' Rhino.Geometry.Line' Rhino.Geometry.Polyline' Rhino.Geometry.Cone' Rhino.Geometry.Cylinder' Rhino.Geometry.Sphere' Rhino.Geometry.Torus,Rhino.Geometry.Brep' Rhino.Geometry.Cone' Rhino.Geometry.Cylinder' Rhino.Geometry.Sphere' Rhino.Geometry.Torus' Rhino.Geometry.Collections.Brep
Rhino.Geometry,RTreeEventArgs,3,1,8,0,0,76,1,0,0,0,0,1,,Rhino.Geometry.RTree
Rhino.Geometry,RTree,5,25,1,0,21,384,42,0,0,0.12,8,0,Rhino.Geometry.Mesh' Rhino.Geometry.PointCloud' Rhino.Geometry.Point3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Point2d' Rhino.Geometry.Callbackholder' Rhino.Geometry.RTreeEventArgs' Rhino.Geometry.Sphere,
Rhino.Geometry,Callbackholder,0,0,4,0,0,7,0,0,0,-1,0,1,,Rhino.Geometry.RTree
Rhino.Geometry,Sphere,2,20,9,0,20,415,29,0,1,0.2,9,11,Rhino.Geometry.Plane' Rhino.Geometry.Point3d' Rhino.Geometry.Circle' Rhino.RhinoMath' Rhino.Geometry.Vector3d' Rhino.Geometry.Transform' Rhino.Geometry.Brep' Rhino.Geometry.NurbsSurface' Rhino.Geometry.RevSurface,Rhino.Geometry.Brep' Rhino.Geometry.NurbsSurface' Rhino.Geometry.RevSurface' Rhino.Geometry.RTree' Rhino.Geometry.Surface' Rhino.DocObjects.ViewportInfo' Rhino.FileIO.File3dmObjectTable' Rhino.Render.TextureMapping' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.NurbsSurface' Rhino.Geometry.Intersect.Intersection
Rhino.Geometry,SumSurface,0,4,0,0,1,35,5,0,1,-1,1,0,Rhino.Geometry.Curve,
Rhino.Geometry,IsoStatus,0,0,0,0,0,31,0,0,0,-1,0,3,,Rhino.Geometry.BrepTrimList' Rhino.Geometry.Surface' Rhino.Geometry.Collections.BrepTrimList
Rhino.Geometry,SurfaceCurvature,9,5,5,0,3,139,8,0,0,0.4,4,1,Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.Geometry.Circle,Rhino.Geometry.Surface
Rhino.Geometry,Surface,4,57,1,0,51,1215,77,7,2,0.74,20,13,Rhino.Geometry.SurfaceOfHolder' Rhino.Geometry.SurfaceHolder' Rhino.Geometry.GeometryBase' Rhino.Geometry.Interval' Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.Geometry.Plane' Rhino.Geometry.SurfaceCurvature' Rhino.Geometry.IsoStatus' Rhino.Geometry.Curve' Rhino.Geometry.BoundingBox' Rhino.Geometry.Continuity' Rhino.Geometry.Brep' Rhino.Geometry.NurbsSurface' Rhino.RhinoMath' Rhino.Geometry.Sphere' Rhino.Geometry.Cylinder' Rhino.Geometry.Cone' Rhino.Geometry.Torus' Rhino.Runtime.InteropWrappers.SimpleArraySurfacePointer,Rhino.Runtime.Interop' Rhino.Geometry.Extrusion' Rhino.Geometry.Brep' Rhino.Geometry.BrepFace' Rhino.Geometry.BrepFaceList' Rhino.Geometry.Mesh' Rhino.FileIO.File3dmObjectTable' Rhino.Render.Mesh' Rhino.Runtime.InteropWrappers.SimpleArraySurfacePointer' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.BrepFaceList' Rhino.Geometry.Collections.Mesh
Rhino.Geometry,SurfaceProxy,0,2,0,0,0,15,2,2,3,-1,0,2,,Rhino.Geometry.BrepFace' Rhino.Geometry.Collections.BrepFace
Rhino.Geometry,Torus,3,4,5,0,4,116,4,0,1,0.75,4,4,Rhino.Geometry.Plane' Rhino.Geometry.NurbsSurface' Rhino.Geometry.RevSurface' Rhino.RhinoMath,Rhino.Geometry.NurbsSurface' Rhino.Geometry.RevSurface' Rhino.Geometry.Surface' Rhino.Geometry.Collections.NurbsSurface
Rhino.Geometry,Transform,16,28,21,0,28,743,40,0,0,0.64,5,40,Rhino.Geometry.Vector3d' Rhino.Geometry.Point3d' Rhino.Geometry.Plane' Rhino.RhinoMath' Rhino.Geometry.BoundingBox,Rhino.Runtime.Interop' Rhino.Geometry.Arc' Rhino.Geometry.Extrusion' Rhino.Geometry.BoundingBox' Rhino.Geometry.Box' Rhino.Geometry.Circle' Rhino.Geometry.Curve' Rhino.Geometry.Point3f' Rhino.Geometry.Vector3f' Rhino.Geometry.GeometryBase' Rhino.Geometry.InstanceReferenceGeometry' Rhino.Geometry.Line' Rhino.Geometry.Matrix' Rhino.Geometry.Mesh' Rhino.Geometry.NurbsCurve' Rhino.Geometry.Plane' Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Vector3d' Rhino.Geometry.Quaternion' Rhino.Geometry.Rectangle3d' Rhino.Geometry.Sphere' Rhino.DocObjects.EarthAnchorPoint' Rhino.DocObjects.ViewportInfo' Rhino.FileIO.EarthAnchorPoint' Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Render.EarthAnchorPoint' Rhino.Render.Mesh' Rhino.Display.EarthAnchorPoint' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.Collections.Point3dList' Rhino.Collections.CurveList' Rhino.Geometry.Collections.Mesh' Rhino.Geometry.Collections.NurbsCurve' Rhino.Geometry.Intersect.Intersection' Rhino.DocObjects.Custom.UserData
Rhino.Geometry,TransformSimilarityType,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Geometry,SpaceMorph,3,2,3,0,2,96,3,0,0,1,2,0,Rhino.Geometry.GeometryBase' Rhino.Geometry.Point3d,
Rhino.Geometry,Interpolator,1,12,1,0,10,232,30,0,0,0.5,0,0,,
Rhino.DocObjects,NamespaceDoc,0,0,0,0,0,10,0,0,0,-1,0,0,,
Rhino.DocObjects,ConstructionPlane,13,4,14,0,1,199,5,0,0,0.5,2,3,Rhino.Geometry.Plane' Rhino.Runtime.InteropWrappers.StringHolder,Rhino.FileIO.ConstructionPlane' Rhino.Render.ConstructionPlane' Rhino.Display.ConstructionPlane
Rhino.DocObjects,ViewInfo,5,7,2,0,1,132,12,0,0,0,2,3,Rhino.DocObjects.ViewportInfo' Rhino.FileIO.File3dm,Rhino.DocObjects.ViewportInfo' Rhino.FileIO.File3dmViewTable' localize_3dm.Program
Rhino.DocObjects,EarthAnchorPoint,4,9,9,0,4,253,10,0,0,0,3,0,Rhino.Geometry.Plane' Rhino.Geometry.Transform' Rhino.UnitSystem,
Rhino.DocObjects,BasepointZero,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.DocObjects,RenderSettings,19,12,19,0,2,343,15,0,0,0.75,0,0,,
Rhino.DocObjects,BackgroundStyle,0,0,0,0,0,11,0,0,0,-1,0,0,,
Rhino.DocObjects,File3dmSettings,7,5,12,0,0,242,5,0,0,0.6,1,0,Rhino.FileIO.File3dm,
Rhino.DocObjects,TextureType,0,0,0,0,0,18,0,0,0,-1,0,0,,
Rhino.DocObjects,TextureCombineMode,0,0,0,0,0,20,0,0,0,-1,0,0,,
Rhino.DocObjects,TextureUvwWrapping,0,0,0,0,0,11,0,0,0,-1,0,1,,Rhino.DocObjects.Texture
Rhino.DocObjects,Texture,4,8,11,0,3,323,9,0,1,0.88,2,1,Rhino.DocObjects.Material' Rhino.DocObjects.TextureUvwWrapping,Rhino.DocObjects.Material
Rhino.DocObjects,ViewportInfo,29,58,41,0,48,1419,74,0,0,0,11,5,Rhino.DocObjects.ViewInfo' Rhino.Runtime.CommonObject' Rhino.Geometry.Vector3d' Rhino.Geometry.Point3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Sphere' Rhino.Geometry.Plane' Rhino.Geometry.Transform' Rhino.Geometry.Line' Rhino.Geometry.GeometryBase' Rhino.RhinoMath,Rhino.Runtime.Interop' Rhino.DocObjects.ViewInfo' Rhino.FileIO.ViewInfo' Rhino.Render.ViewInfo' Rhino.Display.ViewInfo
Rhino.DocObjects,DimensionStyleArrowType,0,0,0,0,0,19,0,0,0,-1,0,0,,
Rhino.DocObjects,DimensionStyle,17,11,22,0,2,301,13,0,1,0.64,2,2,Rhino.FileIO.File3dm' Rhino.Runtime.CommonObject,Rhino.FileIO.File3dmDimStyleTable' localize_3dm.Program
Rhino.DocObjects,HatchPatternFillType,0,0,0,0,0,6,0,0,0,-1,0,0,,
Rhino.DocObjects,HatchPattern,1,7,4,0,1,207,9,0,1,0.71,2,2,Rhino.FileIO.File3dm' Rhino.Runtime.CommonObject,Rhino.FileIO.File3dmHatchPatternTable' localize_3dm.Program
Rhino.DocObjects,InstanceDefinitionUpdateType,0,0,0,0,0,36,0,0,0,-1,0,0,,
Rhino.DocObjects,InstanceDefinitionLayerStyle,0,0,0,0,0,6,0,0,0,-1,0,0,,
Rhino.DocObjects,InstanceDefinitionArchiveFileStatus,0,0,0,0,0,31,0,0,0,-1,0,0,,
Rhino.DocObjects,Layer,11,23,18,0,13,679,26,0,1,0.48,3,2,Rhino.FileIO.File3dm' Rhino.DocObjects.LayerHolder' Rhino.Runtime.CommonObject,Rhino.FileIO.File3dmLayerTable' localize_3dm.Program
Rhino.DocObjects,LayerHolder,1,2,0,0,2,12,2,0,0,0,0,1,,Rhino.DocObjects.Layer
Rhino.DocObjects,Linetype,3,14,8,0,7,263,17,0,1,0.5,2,2,Rhino.FileIO.File3dm' Rhino.Runtime.CommonObject,Rhino.FileIO.File3dmLinetypeTable' localize_3dm.Program
Rhino.DocObjects,MaterialRef,2,6,7,0,1,94,7,0,0,0.67,1,1,Rhino.DocObjects.MaterialRefs,Rhino.DocObjects.MaterialRefs
Rhino.DocObjects,MaterialRefCreateParams,0,0,6,0,0,28,0,0,0,-1,0,1,,Rhino.DocObjects.MaterialRefs
Rhino.DocObjects,MaterialRefs,0,13,7,0,11,359,23,0,0,-1,4,3,Rhino.DocObjects.ObjectAttributes' Rhino.DocObjects.MaterialRefCreateParams' Rhino.DocObjects.MaterialRef' Rhino.DocObjects.MaterialRefDictionaryEnumerator,Rhino.DocObjects.MaterialRef' Rhino.DocObjects.MaterialRefDictionaryEnumerator' Rhino.DocObjects.ObjectAttributes
Rhino.DocObjects,MaterialRefDictionaryEnumerator,3,4,2,0,3,40,6,0,0,0.5,1,1,Rhino.DocObjects.MaterialRefs,Rhino.DocObjects.MaterialRefs
Rhino.DocObjects,MaterialHolder,3,4,1,0,4,27,4,0,0,0.5,1,1,Rhino.DocObjects.Material,Rhino.DocObjects.Material
Rhino.DocObjects,Material,18,35,17,0,19,529,41,0,1,0.43,5,4,Rhino.DocObjects.MaterialHolder' Rhino.FileIO.File3dm' Rhino.Runtime.CommonObject' Rhino.Runtime.Interop' Rhino.DocObjects.Texture,Rhino.DocObjects.Texture' Rhino.DocObjects.MaterialHolder' Rhino.FileIO.File3dmMaterialTable' localize_3dm.Program
Rhino.DocObjects,SelectionMethod,0,0,0,0,0,21,0,0,0,-1,0,0,,
Rhino.DocObjects,ObjectAttributes,22,25,24,0,12,754,28,0,1,0.96,4,4,Rhino.DocObjects.MaterialRefs' Rhino.FileIO.File3dmObject' Rhino.Runtime.InteropWrappers.StringHolder' Rhino.Runtime.Interop,Rhino.DocObjects.MaterialRefs' Rhino.FileIO.File3dmObject' Rhino.FileIO.File3dmObjectTable' localize_3dm.Program
Rhino.FileIO,File3dmTypeCodes,204,0,0,204,0,605,0,0,0,-1,0,1,,example_read.Program
Rhino.FileIO,File3dmNotes,5,3,4,0,1,148,5,0,0,0.67,1,2,Rhino.FileIO.File3dm,Rhino.FileIO.File3dm' localize_3dm.Program
Rhino.FileIO,ConstructionPlane,13,4,14,0,1,199,5,0,0,0.5,3,0,Rhino.Geometry.Plane' Rhino.DocObjects.ConstructionPlane' Rhino.Runtime.InteropWrappers.StringHolder,
Rhino.FileIO,ViewInfo,5,7,2,0,1,132,12,0,0,0.57,2,0,Rhino.DocObjects.ViewportInfo' Rhino.FileIO.File3dm,
Rhino.FileIO,EarthAnchorPoint,4,9,9,0,4,253,10,0,0,0.67,3,0,Rhino.Geometry.Plane' Rhino.Geometry.Transform' Rhino.UnitSystem,
Rhino.FileIO,BasepointZero,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.FileIO,RenderSettings,19,12,19,0,2,343,15,0,0,0.75,0,0,,
Rhino.FileIO,BackgroundStyle,0,0,0,0,0,11,0,0,0,-1,0,0,,
Rhino.FileIO,File3dmSettings,7,5,12,0,0,242,5,0,0,0,1,1,Rhino.FileIO.File3dm,Rhino.FileIO.File3dm
Rhino.FileIO,ArchivableDictionary,4,114,10,0,97,1840,163,0,0,0.87,21,0,Rhino.DocObjects.Custom.UserData' Rhino.Collections.ArchivableDictionary' Rhino.Collections.ItemType' Rhino.FileIO.BinaryArchiveReader' Rhino.Geometry.Interval' Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Point4d' Rhino.Geometry.Vector2d' Rhino.Geometry.Vector3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Ray3d' Rhino.Geometry.Transform' Rhino.Geometry.Plane' Rhino.Geometry.Line' Rhino.Geometry.Point3f' Rhino.Geometry.Vector3f' Rhino.Geometry.GeometryBase' Rhino.Geometry.MeshingParameters' Rhino.Collections.DictionaryItem' Rhino.FileIO.BinaryArchiveWriter,
Rhino.FileIO,ItemType,0,0,0,0,0,64,0,0,0,-1,0,0,,
Rhino.FileIO,DictionaryItem,2,2,0,2,2,20,3,0,0,0,2,0,Rhino.Collections.ItemType' Rhino.Collections.DictionaryItem,
Rhino.FileIO,BinaryArchiveException,0,1,0,0,1,10,1,0,0,-1,0,0,,
Rhino.FileIO,BinaryArchiveWriter,2,54,2,0,47,659,106,0,0,0,16,6,Rhino.Collections.ArchivableDictionary' Rhino.Geometry.Interval' Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Point4d' Rhino.Geometry.Vector2d' Rhino.Geometry.Vector3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Ray3d' Rhino.Geometry.Transform' Rhino.Geometry.Plane' Rhino.Geometry.Line' Rhino.Geometry.Point3f' Rhino.Geometry.Vector3f' Rhino.Geometry.MeshingParameters' Rhino.Geometry.GeometryBase,Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveFile' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveFile' Rhino.DocObjects.Custom.UserData' Rhino.DocObjects.Custom.UserDictionary
Rhino.FileIO,BinaryArchiveReader,2,58,2,0,50,860,121,0,0,0,18,7,Rhino.Collections.ArchivableDictionary' Rhino.Runtime.InteropWrappers.StringHolder' Rhino.Geometry.Interval' Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Point4d' Rhino.Geometry.Vector2d' Rhino.Geometry.Vector3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Ray3d' Rhino.Geometry.Transform' Rhino.Geometry.Plane' Rhino.Geometry.Line' Rhino.Geometry.Point3f' Rhino.Geometry.Vector3f' Rhino.Geometry.MeshingParameters' Rhino.Geometry.GeometryBase' Rhino.FileIO.TextLog,Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveFile' Rhino.Collections.ArchivableDictionary' Rhino.Collections.BinaryArchiveFile' Rhino.DocObjects.Custom.UserData' Rhino.DocObjects.Custom.UserDictionary' example_read.Program
Rhino.FileIO,BinaryArchiveMode,0,0,0,0,0,9,0,0,0,-1,0,3,,Rhino.FileIO.BinaryArchiveFile' Rhino.Collections.BinaryArchiveFile' example_read.Program
Rhino.FileIO,BinaryArchiveFile,5,5,2,0,4,76,9,0,0,0,3,1,Rhino.FileIO.BinaryArchiveMode' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.BinaryArchiveWriter,example_read.Program
Rhino.FileIO,SerializationOptions,0,1,2,0,1,23,1,0,0,-1,0,1,,Rhino.Runtime.CommonObject
Rhino.FileIO,File3dm,19,27,22,0,20,863,36,0,0,0.33,18,29,Rhino.FileIO.File3dmObjectTable' Rhino.FileIO.File3dmMaterialTable' Rhino.FileIO.File3dmLinetypeTable' Rhino.FileIO.File3dmLayerTable' Rhino.FileIO.File3dmDimStyleTable' Rhino.FileIO.File3dmHatchPatternTable' Rhino.FileIO.File3dmInstanceDefinitionTable' Rhino.FileIO.File3dmPlugInDataTable' Rhino.FileIO.File3dmViewTable' Rhino.FileIO.File3dmHistoryRecordTable' Rhino.FileIO.File3dmNotes' Rhino.FileIO.File3dmSettings' Rhino.FileIO.TableTypeFilter' Rhino.FileIO.ObjectTypeFilter' Rhino.Runtime.InteropWrappers.StringHolder' Rhino.FileIO.File3dmWriteOptions' Rhino.FileIO.TextLog' Rhino.Runtime.InteropWrappers.SimpleArrayInt,Rhino.Geometry.InstanceDefinitionGeometry' Rhino.DocObjects.ViewInfo' Rhino.DocObjects.File3dmSettings' Rhino.DocObjects.DimensionStyle' Rhino.DocObjects.HatchPattern' Rhino.DocObjects.Layer' Rhino.DocObjects.Linetype' Rhino.DocObjects.Material' Rhino.FileIO.File3dmNotes' Rhino.FileIO.ViewInfo' Rhino.FileIO.File3dmSettings' Rhino.FileIO.File3dmObject' Rhino.FileIO.File3dmObjectTable' Rhino.FileIO.File3dmPlugInDataTable' Rhino.FileIO.File3dmHistoryRecordTable' Rhino.FileIO.File3dmMaterialTable' Rhino.FileIO.File3dmLinetypeTable' Rhino.FileIO.File3dmLayerTable' Rhino.FileIO.File3dmDimStyleTable' Rhino.FileIO.File3dmHatchPatternTable' Rhino.FileIO.File3dmInstanceDefinitionTable' Rhino.FileIO.File3dmViewTable' Rhino.Render.ViewInfo' Rhino.Render.File3dmSettings' Rhino.Display.ViewInfo' Rhino.Display.File3dmSettings' example_read.Program' localize_3dm.Program' example_read.Program
Rhino.FileIO,TableTypeFilter,0,0,0,0,0,41,0,0,0,-1,0,1,,Rhino.FileIO.File3dm
Rhino.FileIO,ObjectTypeFilter,0,0,0,0,0,35,0,0,0,-1,0,1,,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmWriteOptions,0,1,4,0,1,29,1,0,0,-1,0,1,,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmObject,4,3,3,0,0,56,3,0,0,0,3,4,Rhino.FileIO.File3dm' Rhino.Geometry.GeometryBase' Rhino.DocObjects.ObjectAttributes,Rhino.Geometry.GeometryBase' Rhino.DocObjects.ObjectAttributes' Rhino.FileIO.File3dmObjectTable' localize_3dm.Program
Rhino.FileIO,File3dmObjectTable,2,65,1,0,63,860,92,0,1,0.09,24,1,Rhino.FileIO.File3dm' Rhino.FileIO.File3dmLayerTable' Rhino.FileIO.File3dmObject' Rhino.Geometry.BoundingBox' Rhino.Geometry.Point3d' Rhino.DocObjects.ObjectAttributes' Rhino.Geometry.Point3f' Rhino.Geometry.PointCloud' Rhino.Collections.Point3dList' Rhino.Geometry.Plane' Rhino.Geometry.LinearDimension' Rhino.Geometry.Line' Rhino.Geometry.Arc' Rhino.Geometry.Circle' Rhino.Geometry.Ellipse' Rhino.Geometry.Sphere' Rhino.Geometry.Curve' Rhino.Geometry.TextDot' Rhino.Geometry.TextJustification' Rhino.Geometry.Surface' Rhino.Geometry.Extrusion' Rhino.Geometry.Mesh' Rhino.Geometry.Brep' Rhino.Geometry.Hatch,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmPlugInData,1,1,1,0,0,15,1,0,0,0,0,0,,
Rhino.FileIO,File3dmPlugInDataTable,1,5,1,0,3,71,5,0,1,0.6,1,1,Rhino.FileIO.File3dm,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmHistoryRecordTable,1,3,1,0,2,35,3,0,0,0,1,1,Rhino.FileIO.File3dm,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmMaterialTable,1,12,2,0,10,110,20,0,1,0.42,2,1,Rhino.FileIO.File3dm' Rhino.DocObjects.Material,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmLinetypeTable,1,12,2,0,10,107,20,0,1,0.42,2,1,Rhino.FileIO.File3dm' Rhino.DocObjects.Linetype,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmLayerTable,1,12,2,0,10,107,20,0,1,0.42,2,2,Rhino.FileIO.File3dm' Rhino.DocObjects.Layer,Rhino.FileIO.File3dm' Rhino.FileIO.File3dmObjectTable
Rhino.FileIO,File3dmDimStyleTable,1,12,2,0,10,107,20,0,1,0.42,2,1,Rhino.FileIO.File3dm' Rhino.DocObjects.DimensionStyle,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmHatchPatternTable,1,12,2,0,10,107,20,0,1,0.42,2,1,Rhino.FileIO.File3dm' Rhino.DocObjects.HatchPattern,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmInstanceDefinitionTable,1,13,2,0,11,123,21,0,1,0.38,2,1,Rhino.FileIO.File3dm' Rhino.Geometry.InstanceDefinitionGeometry,Rhino.FileIO.File3dm
Rhino.FileIO,File3dmViewTable,2,12,2,0,10,115,20,0,1,0.42,2,1,Rhino.FileIO.File3dm' Rhino.DocObjects.ViewInfo,Rhino.FileIO.File3dm
Rhino.FileIO,TextLog,2,13,1,0,10,166,17,0,0,0,0,4,,Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.File3dm' Rhino.Collections.BinaryArchiveReader' example_read.Program
Rhino.FileIO,FileType,0,1,2,0,1,10,1,0,0,-1,0,0,,
Rhino.Render,ConstructionPlane,13,4,14,0,1,199,5,0,0,0.5,3,0,Rhino.Geometry.Plane' Rhino.DocObjects.ConstructionPlane' Rhino.Runtime.InteropWrappers.StringHolder,
Rhino.Render,ViewInfo,5,7,2,0,1,132,12,0,0,0.57,2,0,Rhino.DocObjects.ViewportInfo' Rhino.FileIO.File3dm,
Rhino.Render,EarthAnchorPoint,4,9,9,0,4,253,10,0,0,0.67,3,0,Rhino.Geometry.Plane' Rhino.Geometry.Transform' Rhino.UnitSystem,
Rhino.Render,BasepointZero,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Render,RenderSettings,19,12,19,0,2,343,15,0,0,0,0,0,,
Rhino.Render,BackgroundStyle,0,0,0,0,0,11,0,0,0,-1,0,0,,
Rhino.Render,File3dmSettings,7,5,12,0,0,242,5,0,0,0.6,1,0,Rhino.FileIO.File3dm,
Rhino.Render,CachedTextureCoordinates,0,15,4,0,10,255,22,0,1,-1,3,5,Rhino.Geometry.Mesh' Rhino.Geometry.Point3d' Rhino.Render.CachedTextureCoordinatesEnumerator,Rhino.Geometry.CachedTextureCoordinates' Rhino.Geometry.Mesh' Rhino.Render.Mesh' Rhino.Geometry.Collections.CachedTextureCoordinates' Rhino.Geometry.Collections.Mesh
Rhino.Render,CachedTextureCoordinatesEnumerator,3,4,2,0,3,40,4,0,0,0.5,0,3,,Rhino.Geometry.CachedTextureCoordinates' Rhino.Render.CachedTextureCoordinates' Rhino.Geometry.Collections.CachedTextureCoordinates
Rhino.Render,MappingTag,0,0,4,0,0,21,0,0,0,-1,0,0,,
Rhino.Render,MeshingParameterStyle,0,0,0,0,0,13,0,0,0,-1,0,0,,
Rhino.Render,MeshingParameters,14,12,19,0,2,358,13,0,0,0.67,0,0,,
Rhino.Render,MeshPart,6,1,6,0,0,30,1,0,0,0,0,0,,
Rhino.Render,Mesh,56,25,12,0,17,1418,37,0,2,0.96,17,0,Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshTopologyVertexList' Rhino.Geometry.Collections.MeshTopologyEdgeList' Rhino.Geometry.Collections.MeshVertexNormalList' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Collections.MeshFaceNormalList' Rhino.Geometry.Collections.MeshVertexColorList' Rhino.Geometry.Collections.MeshTextureCoordinateList' Rhino.Geometry.MeshHolder' Rhino.Geometry.GeometryBase' Rhino.Geometry.Mesh' Rhino.Geometry.Surface' Rhino.Render.TextureMapping' Rhino.Geometry.Transform' Rhino.Render.CachedTextureCoordinates' Rhino.Geometry.Point3d' Rhino.Geometry.MeshPart,
Rhino.Render,MeshVertexList,1,29,1,0,27,505,55,0,1,0.34,6,0,Rhino.Geometry.Mesh' Rhino.Geometry.Point3f' Rhino.Geometry.Point3d' Rhino.Runtime.InteropWrappers.SimpleArrayInt' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.MeshFace,
Rhino.Render,MeshTopologyVertexList,1,12,1,0,10,211,20,0,1,0.33,2,0,Rhino.Geometry.Mesh' Rhino.Runtime.InteropWrappers.SimpleArrayInt,
Rhino.Render,MeshTopologyEdgeList,1,12,1,0,11,210,20,0,0,0,4,0,Rhino.Geometry.Mesh' Rhino.IndexPair' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Line,
Rhino.Render,MeshVertexNormalList,1,18,1,0,15,242,20,0,1,0.67,3,0,Rhino.Geometry.Mesh' Rhino.Geometry.Vector3f' Rhino.Geometry.Vector3d,
Rhino.Render,MeshFaceList,1,26,3,0,24,482,43,0,1,0.35,6,0,Rhino.Geometry.Mesh' Rhino.Geometry.MeshFace' Rhino.Geometry.Point3f' Rhino.Geometry.BoundingBox' Rhino.Geometry.Point3d' Rhino.Geometry.Collections.MeshTopologyEdgeList,
Rhino.Render,MeshFaceNormalList,1,14,1,0,12,188,14,0,1,0.71,3,0,Rhino.Geometry.Mesh' Rhino.Geometry.Vector3d' Rhino.Geometry.Vector3f,
Rhino.Render,MeshVertexColorList,1,13,2,0,10,231,17,0,1,0.69,3,0,Rhino.Geometry.Mesh' Rhino.Geometry.MeshFace' Rhino.Geometry.Collections.MeshVertexList,
Rhino.Render,MeshTextureCoordinateList,1,19,1,0,16,251,21,0,1,0.63,5,0,Rhino.Geometry.Mesh' Rhino.Geometry.Point2f' Rhino.Geometry.Point3d' Rhino.Geometry.Point3f' Rhino.Render.TextureMapping,
Rhino.Render,MeshFace,4,7,8,0,7,211,22,0,0,0,1,0,Rhino.Geometry.MeshFace,
Rhino.Render,TextureMappingType,0,0,0,0,0,21,0,0,0,-1,0,0,,
Rhino.Render,TextureMapping,0,12,5,0,8,364,16,0,1,-1,4,6,Rhino.Geometry.Plane' Rhino.Geometry.Interval' Rhino.Geometry.Sphere' Rhino.Geometry.Cylinder,Rhino.Geometry.Mesh' Rhino.Geometry.MeshTextureCoordinateList' Rhino.Render.Mesh' Rhino.Render.MeshTextureCoordinateList' Rhino.Geometry.Collections.Mesh' Rhino.Geometry.Collections.MeshTextureCoordinateList
Rhino.Display,ConstructionPlane,13,4,14,0,1,199,5,0,0,0.5,3,0,Rhino.Geometry.Plane' Rhino.DocObjects.ConstructionPlane' Rhino.Runtime.InteropWrappers.StringHolder,
Rhino.Display,ViewInfo,5,7,2,0,1,132,12,0,0,0.57,2,0,Rhino.DocObjects.ViewportInfo' Rhino.FileIO.File3dm,
Rhino.Display,EarthAnchorPoint,4,9,9,0,4,253,10,0,0,0.67,3,0,Rhino.Geometry.Plane' Rhino.Geometry.Transform' Rhino.UnitSystem,
Rhino.Display,BasepointZero,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Display,RenderSettings,19,12,19,0,2,343,15,0,0,0.75,0,0,,
Rhino.Display,BackgroundStyle,0,0,0,0,0,11,0,0,0,-1,0,0,,
Rhino.Display,File3dmSettings,7,5,12,0,0,242,5,0,0,0.6,1,0,Rhino.FileIO.File3dm,
Rhino.Display,Color4f,4,11,7,0,9,104,11,0,0,0.36,0,0,,
Rhino.Display,ColorHSL,4,9,4,0,8,156,11,0,0,0.56,5,4,Rhino.Display.ColorConverter' Rhino.Display.ColorCMYK' Rhino.Display.ColorXYZ' Rhino.Display.ColorLAB' Rhino.Display.ColorLCH,Rhino.Display.ColorCMYK' Rhino.Display.ColorXYZ' Rhino.Display.ColorLAB' Rhino.Display.ColorLCH
Rhino.Display,ColorCMYK,5,9,5,0,8,197,15,0,0,0.56,5,4,Rhino.Display.ColorConverter' Rhino.Display.ColorHSL' Rhino.Display.ColorXYZ' Rhino.Display.ColorLAB' Rhino.Display.ColorLCH,Rhino.Display.ColorHSL' Rhino.Display.ColorXYZ' Rhino.Display.ColorLAB' Rhino.Display.ColorLCH
Rhino.Display,ColorXYZ,4,8,4,0,7,192,10,0,0,0.38,5,4,Rhino.Display.ColorConverter' Rhino.Display.ColorHSL' Rhino.Display.ColorCMYK' Rhino.Display.ColorLAB' Rhino.Display.ColorLCH,Rhino.Display.ColorHSL' Rhino.Display.ColorCMYK' Rhino.Display.ColorLAB' Rhino.Display.ColorLCH
Rhino.Display,ColorLAB,4,8,4,0,7,149,10,0,0,0.25,5,4,Rhino.Display.ColorXYZ' Rhino.Display.ColorHSL' Rhino.Display.ColorCMYK' Rhino.Display.ColorConverter' Rhino.Display.ColorLCH,Rhino.Display.ColorHSL' Rhino.Display.ColorCMYK' Rhino.Display.ColorXYZ' Rhino.Display.ColorLCH
Rhino.Display,ColorLCH,4,11,4,0,8,167,17,0,0,0.27,5,4,Rhino.Display.ColorLAB' Rhino.Display.ColorHSL' Rhino.Display.ColorCMYK' Rhino.Display.ColorXYZ' Rhino.Display.ColorConverter,Rhino.Display.ColorHSL' Rhino.Display.ColorCMYK' Rhino.Display.ColorXYZ' Rhino.Display.ColorLAB
Rhino.Display,ColorConverter,0,18,0,0,0,371,40,0,0,-1,0,5,,Rhino.Display.ColorHSL' Rhino.Display.ColorCMYK' Rhino.Display.ColorXYZ' Rhino.Display.ColorLAB' Rhino.Display.ColorLCH
Rhino.Display,DefinedViewportProjection,0,0,0,0,0,12,0,0,0,-1,0,0,,
Rhino.Display,ViewportType,0,0,0,0,0,6,0,0,0,-1,0,0,,
Rhino.Collections,ArchivableDictionary,4,114,10,0,97,1840,163,0,0,0.04,20,6,Rhino.DocObjects.Custom.UserData' Rhino.Collections.ItemType' Rhino.FileIO.BinaryArchiveReader' Rhino.Geometry.Interval' Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Point4d' Rhino.Geometry.Vector2d' Rhino.Geometry.Vector3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Ray3d' Rhino.Geometry.Transform' Rhino.Geometry.Plane' Rhino.Geometry.Line' Rhino.Geometry.Point3f' Rhino.Geometry.Vector3f' Rhino.Geometry.GeometryBase' Rhino.Geometry.MeshingParameters' Rhino.Collections.DictionaryItem' Rhino.FileIO.BinaryArchiveWriter,Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Collections.BinaryArchiveWriter' Rhino.Collections.BinaryArchiveReader' Rhino.DocObjects.Custom.UserDictionary
Rhino.Collections,ItemType,0,0,0,0,0,64,0,0,0,-1,0,4,,Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.DictionaryItem' Rhino.Collections.ArchivableDictionary' Rhino.Collections.DictionaryItem
Rhino.Collections,DictionaryItem,2,2,0,2,2,20,3,0,0,0,1,3,Rhino.Collections.ItemType,Rhino.FileIO.ArchivableDictionary' Rhino.FileIO.DictionaryItem' Rhino.Collections.ArchivableDictionary
Rhino.Collections,BinaryArchiveException,0,1,0,0,1,10,1,0,0,-1,0,0,,
Rhino.Collections,BinaryArchiveWriter,2,54,2,0,47,659,106,0,0,0.19,16,0,Rhino.Collections.ArchivableDictionary' Rhino.Geometry.Interval' Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Point4d' Rhino.Geometry.Vector2d' Rhino.Geometry.Vector3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Ray3d' Rhino.Geometry.Transform' Rhino.Geometry.Plane' Rhino.Geometry.Line' Rhino.Geometry.Point3f' Rhino.Geometry.Vector3f' Rhino.Geometry.MeshingParameters' Rhino.Geometry.GeometryBase,
Rhino.Collections,BinaryArchiveReader,2,58,2,0,50,860,121,0,0,0.22,18,0,Rhino.Collections.ArchivableDictionary' Rhino.Runtime.InteropWrappers.StringHolder' Rhino.Geometry.Interval' Rhino.Geometry.Point2d' Rhino.Geometry.Point3d' Rhino.Geometry.Point4d' Rhino.Geometry.Vector2d' Rhino.Geometry.Vector3d' Rhino.Geometry.BoundingBox' Rhino.Geometry.Ray3d' Rhino.Geometry.Transform' Rhino.Geometry.Plane' Rhino.Geometry.Line' Rhino.Geometry.Point3f' Rhino.Geometry.Vector3f' Rhino.Geometry.MeshingParameters' Rhino.Geometry.GeometryBase' Rhino.FileIO.TextLog,
Rhino.Collections,BinaryArchiveMode,0,0,0,0,0,9,0,0,0,-1,0,0,,
Rhino.Collections,BinaryArchiveFile,5,5,2,0,4,76,9,0,0,0.4,3,0,Rhino.FileIO.BinaryArchiveMode' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.BinaryArchiveWriter,
Rhino.Collections,SerializationOptions,0,1,2,0,1,23,1,0,0,-1,0,0,,
Rhino.Collections,IRhinoTable,0,0,1,0,0,5,0,50,0,-1,0,0,,
Rhino.Collections,TableEnumerator<TABLE;TABLE_TYPE>,3,4,2,0,3,47,7,0,0,0.5,0,0,,
Rhino.Collections,RhinoList<T>,4,67,10,0,56,1375,172,0,0,0.34,1,0,Rhino.Collections.Enumerator,
Rhino.Collections,FunctorComparer<Q>,1,2,0,0,2,14,2,0,0,0,0,0,,
Rhino.Collections,Enumerator,4,5,2,0,2,66,8,0,0,0.4,0,1,,Rhino.Collections.RhinoList<T>
Rhino.Collections,ListDebuggerDisplayProxy<T>,1,1,1,0,1,21,2,0,0,0,0,0,,
Rhino.Collections,Point3dList,3,14,4,0,12,331,30,1,0,0.86,6,11,Rhino.Collections.XAccess' Rhino.Collections.YAccess' Rhino.Collections.ZAccess' Rhino.Geometry.Point3d' Rhino.Runtime.InteropWrappers.SimpleArrayPoint3d' Rhino.Geometry.Transform,Rhino.Geometry.Curve' Rhino.Geometry.NurbsCurve' Rhino.Geometry.Point3d' Rhino.Geometry.PointCloud' Rhino.Geometry.PolylineCurve' Rhino.Geometry.Rectangle3d' Rhino.FileIO.File3dmObjectTable' Rhino.Collections.XAccess' Rhino.Collections.YAccess' Rhino.Collections.ZAccess' Rhino.Geometry.Collections.NurbsCurve
Rhino.Collections,XAccess,1,1,0,0,0,21,2,0,0,0,1,1,Rhino.Collections.Point3dList,Rhino.Collections.Point3dList
Rhino.Collections,YAccess,1,1,0,0,0,21,2,0,0,0,1,1,Rhino.Collections.Point3dList,Rhino.Collections.Point3dList
Rhino.Collections,ZAccess,1,1,0,0,0,21,2,0,0,0,1,1,Rhino.Collections.Point3dList,Rhino.Collections.Point3dList
Rhino.Collections,CurveList,0,14,0,0,14,137,19,0,0,-1,7,2,Rhino.Geometry.Line' Rhino.Geometry.Circle' Rhino.Geometry.Arc' Rhino.Geometry.NurbsCurve' Rhino.Geometry.Ellipse' Rhino.Geometry.Curve' Rhino.Geometry.Transform,Rhino.Geometry.Brep' Rhino.Geometry.Collections.Brep
Rhino.Runtime.InteropWrappers,INTERNAL_ComponentIndexArray,1,5,1,1,4,40,7,0,0,0,1,0,Rhino.Geometry.ComponentIndex,
Rhino.Runtime.InteropWrappers,StringHolder,1,7,0,0,6,69,8,0,0,0,0,12,,Rhino.Runtime.HostUtils' Rhino.Runtime.CommonObject' Rhino.Geometry.Brep' Rhino.DocObjects.ConstructionPlane' Rhino.DocObjects.ObjectAttributes' Rhino.FileIO.ConstructionPlane' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.File3dm' Rhino.Render.ConstructionPlane' Rhino.Display.ConstructionPlane' Rhino.Collections.BinaryArchiveReader' Rhino.Geometry.Collections.Brep
Rhino.Runtime.InteropWrappers,SimpleArrayInt,1,7,1,0,6,82,10,0,0,0,0,11,,Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepFace' Rhino.Geometry.MeshVertexList' Rhino.Geometry.MeshTopologyVertexList' Rhino.FileIO.File3dm' Rhino.Render.MeshVertexList' Rhino.Render.MeshTopologyVertexList' Rhino.Geometry.Collections.BrepEdge' Rhino.Geometry.Collections.BrepFace' Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshTopologyVertexList
Rhino.Runtime.InteropWrappers,SimpleArrayGuid,1,6,1,0,5,64,8,0,0,0,0,1,,Rhino.Geometry.InstanceDefinitionGeometry
Rhino.Runtime.InteropWrappers,SimpleArrayInterval,1,6,1,0,5,64,8,0,0,0,1,0,Rhino.Geometry.Interval,
Rhino.Runtime.InteropWrappers,SimpleArrayDouble,1,7,1,0,6,72,9,0,0,0,0,1,,Rhino.Geometry.Curve
Rhino.Runtime.InteropWrappers,SimpleArrayPoint2d,1,6,1,0,5,82,8,0,0,0,1,0,Rhino.Geometry.Point2d,
Rhino.Runtime.InteropWrappers,SimpleArrayPoint3d,1,6,1,0,5,82,8,0,0,0,1,5,Rhino.Geometry.Point3d,Rhino.Geometry.Brep' Rhino.Geometry.Curve' Rhino.Geometry.Polyline' Rhino.Collections.Point3dList' Rhino.Geometry.Collections.Brep
Rhino.Runtime.InteropWrappers,SimpleArrayLine,1,6,1,0,5,70,8,0,0,0,1,0,Rhino.Geometry.Line,
Rhino.Runtime.InteropWrappers,SimpleArraySurfacePointer,1,6,0,0,5,72,10,0,0,0,2,1,Rhino.Geometry.Surface' Rhino.Geometry.GeometryBase,Rhino.Geometry.Surface
Rhino.Runtime.InteropWrappers,SimpleArrayCurvePointer,1,7,0,0,6,93,15,0,0,0,2,6,Rhino.Geometry.Curve' Rhino.Geometry.GeometryBase,Rhino.Geometry.Brep' Rhino.Geometry.BrepLoopList' Rhino.Geometry.Hatch' Rhino.Geometry.PolyCurve' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepLoopList
Rhino.Runtime.InteropWrappers,SimpleArrayGeometryPointer,1,8,0,0,7,97,13,0,0,0,1,0,Rhino.Geometry.GeometryBase,
Rhino.Runtime.InteropWrappers,SimpleArrayMeshPointer,1,7,1,0,6,113,13,0,0,0,1,0,Rhino.Geometry.Mesh,
Rhino.Runtime.InteropWrappers,SimpleArrayBrepPointer,1,7,1,0,6,95,13,0,0,0,1,0,Rhino.Geometry.Brep,
Rhino.Runtime.InteropWrappers,MeshPointDataStruct,13,0,0,13,0,72,0,0,0,-1,0,2,,Rhino.Geometry.MeshPoint' Rhino.Runtime.InteropWrappers.MeshPoint
Rhino.Runtime.InteropWrappers,MeshPoint,3,1,8,0,0,105,1,0,0,0,2,0,Rhino.Geometry.Mesh' Rhino.Runtime.InteropWrappers.MeshPointDataStruct,
Rhino.Runtime.InteropWrappers,StringWrapper,1,8,2,0,7,89,9,0,0,0.38,0,0,,
Rhino.Geometry.Collections,PipeCapMode,0,0,0,0,0,9,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,LoftType,0,0,0,0,0,30,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,ExtrudeCornerType,0,0,0,0,0,13,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,Brep,29,45,12,0,41,1794,55,0,2,1,23,0,Rhino.Geometry.Collections.BrepVertexList' Rhino.Geometry.Collections.BrepSurfaceList' Rhino.Geometry.Collections.BrepEdgeList' Rhino.Geometry.Collections.BrepTrimList' Rhino.Geometry.Collections.BrepLoopList' Rhino.Geometry.Collections.BrepFaceList' Rhino.Geometry.Collections.BrepCurveList' Rhino.Geometry.Brep' Rhino.Geometry.GeometryBase' Rhino.Geometry.Mesh' Rhino.Geometry.BoundingBox' Rhino.Geometry.Box' Rhino.Geometry.Point3d' Rhino.Geometry.Cylinder' Rhino.Geometry.Sphere' Rhino.Geometry.Cone' Rhino.Geometry.RevSurface' Rhino.Collections.CurveList' Rhino.Geometry.Curve' Rhino.Geometry.Surface' Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer' Rhino.Runtime.InteropWrappers.SimpleArrayPoint3d' Rhino.Runtime.InteropWrappers.StringHolder,
Rhino.Geometry.Collections,PointFaceRelation,0,0,0,0,0,15,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,BrepSolidOrientation,0,0,0,0,0,19,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,EdgeAdjacency,0,0,0,0,0,19,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,BrepVertex,2,3,2,0,0,36,3,0,3,0,1,0,Rhino.Geometry.Brep,
Rhino.Geometry.Collections,BrepEdge,2,5,7,0,3,179,6,0,3,0,3,0,Rhino.Geometry.Brep' Rhino.Runtime.InteropWrappers.SimpleArrayInt' Rhino.Geometry.Interval,
Rhino.Geometry.Collections,BrepTrimType,0,0,0,0,0,43,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,BrepTrim,5,7,7,0,4,214,8,0,3,0,2,0,Rhino.Geometry.Brep' Rhino.Geometry.Interval,
Rhino.Geometry.Collections,BrepLoopType,0,0,0,0,0,29,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,BrepLoop,3,4,5,0,2,93,6,0,2,0,4,0,Rhino.Geometry.Brep' Rhino.Geometry.Collections.BrepTrimList' Rhino.Geometry.GeometryBase' Rhino.Geometry.Curve,
Rhino.Geometry.Collections,BrepFace,3,12,6,0,9,394,17,0,4,0.17,11,0,Rhino.Geometry.Brep' Rhino.Geometry.Collections.BrepLoopList' Rhino.Geometry.SurfaceProxy' Rhino.Geometry.GeometryBase' Rhino.Geometry.Curve' Rhino.Geometry.Interval' Rhino.Geometry.Surface' Rhino.Geometry.Mesh' Rhino.Geometry.MeshType' Rhino.Geometry.MeshHolder' Rhino.Runtime.InteropWrappers.SimpleArrayInt,
Rhino.Geometry.Collections,MeshHolder,3,4,0,0,4,71,6,0,0,0.5,4,0,Rhino.Geometry.BrepFace' Rhino.Geometry.Extrusion' Rhino.Geometry.MeshType' Rhino.Geometry.Brep,
Rhino.Geometry.Collections,SurfaceOfHolder,1,2,0,0,2,13,2,0,0,0,2,0,Rhino.Geometry.BrepFace' Rhino.Geometry.Brep,
Rhino.Geometry.Collections,SurfaceHolder,2,2,0,0,2,15,2,0,0,0,1,0,Rhino.Geometry.Brep,
Rhino.Geometry.Collections,CurveHolder,3,3,0,0,3,22,3,0,0,0,1,0,Rhino.Geometry.Brep,
Rhino.Geometry.Collections,BrepVertexList,1,6,1,0,4,101,9,0,1,0.5,4,2,Rhino.Geometry.Brep' Rhino.Geometry.BrepVertex' Rhino.Geometry.Point3d' Rhino.Geometry.BrepFace,Rhino.Geometry.Brep' Rhino.Geometry.Collections.Brep
Rhino.Geometry.Collections,BrepFaceList,2,14,1,0,12,331,19,0,1,0.21,6,2,Rhino.Geometry.Brep' Rhino.Geometry.GeometryBase' Rhino.Geometry.BrepFace' Rhino.Geometry.Surface' Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepVertex,Rhino.Geometry.Brep' Rhino.Geometry.Collections.Brep
Rhino.Geometry.Collections,BrepSurfaceList,2,3,1,0,1,74,3,0,1,1,1,2,Rhino.Geometry.Brep,Rhino.Geometry.Brep' Rhino.Geometry.Collections.Brep
Rhino.Geometry.Collections,BrepCurveList,3,4,1,0,2,87,4,0,1,0.75,2,2,Rhino.Geometry.Brep' Rhino.Geometry.Curve,Rhino.Geometry.Brep' Rhino.Geometry.Collections.Brep
Rhino.Geometry.Collections,BrepEdgeList,2,8,1,0,6,171,10,0,1,0.5,4,2,Rhino.Geometry.Brep' Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepVertex' Rhino.Geometry.Interval,Rhino.Geometry.Brep' Rhino.Geometry.Collections.Brep
Rhino.Geometry.Collections,BrepTrimList,3,10,1,0,7,186,10,0,1,0.3,7,4,Rhino.Geometry.Brep' Rhino.Geometry.BrepLoop' Rhino.Geometry.BrepTrim' Rhino.Geometry.BrepEdge' Rhino.Geometry.BrepVertex' Rhino.Geometry.IsoStatus' Rhino.Geometry.BrepFace,Rhino.Geometry.Brep' Rhino.Geometry.BrepLoop' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepLoop
Rhino.Geometry.Collections,BrepLoopList,3,8,1,0,5,160,8,0,1,0.38,5,4,Rhino.Geometry.Brep' Rhino.Geometry.BrepFace' Rhino.Geometry.BrepLoop' Rhino.Geometry.BrepLoopType' Rhino.Runtime.InteropWrappers.SimpleArrayCurvePointer,Rhino.Geometry.Brep' Rhino.Geometry.BrepFace' Rhino.Geometry.Collections.Brep' Rhino.Geometry.Collections.BrepFace
Rhino.Geometry.Collections,CachedTextureCoordinates,0,15,4,0,10,255,22,0,1,-1,4,0,Rhino.Render.CachedTextureCoordinates' Rhino.Geometry.Mesh' Rhino.Geometry.Point3d' Rhino.Render.CachedTextureCoordinatesEnumerator,
Rhino.Geometry.Collections,CachedTextureCoordinatesEnumerator,3,4,2,0,3,40,4,0,0,0.5,0,0,,
Rhino.Geometry.Collections,MappingTag,0,0,4,0,0,21,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,MeshingParameterStyle,0,0,0,0,0,13,0,0,0,-1,0,0,,
Rhino.Geometry.Collections,MeshingParameters,14,12,19,0,2,358,13,0,0,0.67,0,0,,
Rhino.Geometry.Collections,MeshPart,6,1,6,0,0,30,1,0,0,0,0,0,,
Rhino.Geometry.Collections,Mesh,56,25,12,0,17,1418,37,0,2,0.96,17,0,Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshTopologyVertexList' Rhino.Geometry.Collections.MeshTopologyEdgeList' Rhino.Geometry.Collections.MeshVertexNormalList' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Collections.MeshFaceNormalList' Rhino.Geometry.Collections.MeshVertexColorList' Rhino.Geometry.Collections.MeshTextureCoordinateList' Rhino.Geometry.MeshHolder' Rhino.Geometry.GeometryBase' Rhino.Geometry.Mesh' Rhino.Geometry.Surface' Rhino.Render.TextureMapping' Rhino.Geometry.Transform' Rhino.Render.CachedTextureCoordinates' Rhino.Geometry.Point3d' Rhino.Geometry.MeshPart,
Rhino.Geometry.Collections,MeshVertexList,1,29,1,0,27,505,55,0,1,0.1,6,6,Rhino.Geometry.Mesh' Rhino.Geometry.Point3f' Rhino.Geometry.Point3d' Rhino.Runtime.InteropWrappers.SimpleArrayInt' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.MeshFace,Rhino.Geometry.Mesh' Rhino.Geometry.MeshVertexColorList' Rhino.Render.Mesh' Rhino.Render.MeshVertexColorList' Rhino.Geometry.Collections.Mesh' Rhino.Geometry.Collections.MeshVertexColorList
Rhino.Geometry.Collections,MeshTopologyVertexList,1,12,1,0,10,211,20,0,1,0.17,2,3,Rhino.Geometry.Mesh' Rhino.Runtime.InteropWrappers.SimpleArrayInt,Rhino.Geometry.Mesh' Rhino.Render.Mesh' Rhino.Geometry.Collections.Mesh
Rhino.Geometry.Collections,MeshTopologyEdgeList,1,12,1,0,11,210,20,0,0,0,4,6,Rhino.Geometry.Mesh' Rhino.IndexPair' Rhino.Geometry.Collections.MeshFaceList' Rhino.Geometry.Line,Rhino.Geometry.Mesh' Rhino.Geometry.MeshFaceList' Rhino.Render.Mesh' Rhino.Render.MeshFaceList' Rhino.Geometry.Collections.Mesh' Rhino.Geometry.Collections.MeshFaceList
Rhino.Geometry.Collections,MeshVertexNormalList,1,18,1,0,15,242,20,0,1,0.11,3,3,Rhino.Geometry.Mesh' Rhino.Geometry.Vector3f' Rhino.Geometry.Vector3d,Rhino.Geometry.Mesh' Rhino.Render.Mesh' Rhino.Geometry.Collections.Mesh
Rhino.Geometry.Collections,MeshFaceList,1,26,3,0,24,482,43,0,1,0.08,6,9,Rhino.Geometry.Mesh' Rhino.Geometry.MeshFace' Rhino.Geometry.Point3f' Rhino.Geometry.BoundingBox' Rhino.Geometry.Point3d' Rhino.Geometry.Collections.MeshTopologyEdgeList,Rhino.Geometry.Mesh' Rhino.Geometry.MeshVertexList' Rhino.Geometry.MeshTopologyEdgeList' Rhino.Render.Mesh' Rhino.Render.MeshVertexList' Rhino.Render.MeshTopologyEdgeList' Rhino.Geometry.Collections.Mesh' Rhino.Geometry.Collections.MeshVertexList' Rhino.Geometry.Collections.MeshTopologyEdgeList
Rhino.Geometry.Collections,MeshFaceNormalList,1,14,1,0,12,188,14,0,1,0.29,3,3,Rhino.Geometry.Mesh' Rhino.Geometry.Vector3d' Rhino.Geometry.Vector3f,Rhino.Geometry.Mesh' Rhino.Render.Mesh' Rhino.Geometry.Collections.Mesh
Rhino.Geometry.Collections,MeshVertexColorList,1,13,2,0,10,231,17,0,1,0.15,3,3,Rhino.Geometry.Mesh' Rhino.Geometry.MeshFace' Rhino.Geometry.Collections.MeshVertexList,Rhino.Geometry.Mesh' Rhino.Render.Mesh' Rhino.Geometry.Collections.Mesh
Rhino.Geometry.Collections,MeshTextureCoordinateList,1,19,1,0,16,251,21,0,1,0.11,5,3,Rhino.Geometry.Mesh' Rhino.Geometry.Point2f' Rhino.Geometry.Point3d' Rhino.Geometry.Point3f' Rhino.Render.TextureMapping,Rhino.Geometry.Mesh' Rhino.Render.Mesh' Rhino.Geometry.Collections.Mesh
Rhino.Geometry.Collections,MeshFace,4,7,8,0,7,211,22,0,0,0,1,0,Rhino.Geometry.MeshFace,
Rhino.Geometry.Collections,NurbsCurve,16,23,5,0,17,530,42,0,2,1,10,0,Rhino.Geometry.Collections.NurbsCurveKnotList' Rhino.Geometry.Collections.NurbsCurvePointList' Rhino.Geometry.NurbsCurve' Rhino.Geometry.Line' Rhino.Geometry.Arc' Rhino.Geometry.Circle' Rhino.Geometry.Transform' Rhino.Geometry.Ellipse' Rhino.Geometry.Point3d' Rhino.Collections.Point3dList,
Rhino.Geometry.Collections,ControlPoint,1,6,3,0,6,118,6,0,1,0,3,0,Rhino.Geometry.Point4d' Rhino.Geometry.Point3d' Rhino.Geometry.ControlPoint,
Rhino.Geometry.Collections,NurbsCurveKnotList,1,12,3,0,9,197,19,0,1,0.33,3,3,Rhino.Geometry.NurbsCurve' Rhino.Geometry.CurveEnd' Rhino.RhinoMath,Rhino.Geometry.NurbsCurve' Rhino.Geometry.NurbsCurveKnotList' Rhino.Geometry.Collections.NurbsCurve
Rhino.Geometry.Collections,NurbsCurvePointList,1,12,2,0,9,198,20,0,1,0.42,6,3,Rhino.Geometry.NurbsCurve' Rhino.Geometry.Polyline' Rhino.Geometry.ControlPoint' Rhino.Geometry.Point4d' Rhino.Geometry.Point3d' Rhino.RhinoMath,Rhino.Geometry.NurbsCurve' Rhino.Geometry.NurbsCurvePointList' Rhino.Geometry.Collections.NurbsCurve
Rhino.Geometry.Collections,NurbsSurface,13,17,6,0,13,514,33,0,3,1,8,0,Rhino.Geometry.Collections.NurbsSurfaceKnotList' Rhino.Geometry.Collections.NurbsSurfacePointList' Rhino.Geometry.NurbsSurface' Rhino.Geometry.Cone' Rhino.Geometry.Cylinder' Rhino.Geometry.Sphere' Rhino.Geometry.Torus' Rhino.Geometry.Curve,
Rhino.Geometry.Collections,MorphControl,0,3,3,0,1,113,3,0,2,-1,1,0,Rhino.Geometry.NurbsCurve,
Rhino.Geometry.Collections,NurbsSurfacePointList,1,9,2,0,6,220,29,0,1,0.44,6,5,Rhino.Geometry.NurbsSurface' Rhino.Geometry.Point2d' Rhino.Geometry.Point4d' Rhino.Geometry.ControlPoint' Rhino.Geometry.Point3d' Rhino.Geometry.Collections.NurbsSrfEnum,Rhino.Geometry.NurbsSurface' Rhino.Geometry.NurbsSurfacePointList' Rhino.Geometry.NurbsSrfEnum' Rhino.Geometry.Collections.NurbsSurface' Rhino.Geometry.Collections.NurbsSrfEnum
Rhino.Geometry.Collections,NurbsSrfEnum,5,4,3,0,4,74,5,0,0,0.75,1,2,Rhino.Geometry.Collections.NurbsSurfacePointList,Rhino.Geometry.NurbsSurfacePointList' Rhino.Geometry.Collections.NurbsSurfacePointList
Rhino.Geometry.Collections,NurbsSurfaceKnotList,2,11,3,0,8,174,17,0,1,0.27,2,3,Rhino.Geometry.NurbsSurface' Rhino.RhinoMath,Rhino.Geometry.NurbsSurface' Rhino.Geometry.NurbsSurfaceKnotList' Rhino.Geometry.Collections.NurbsSurface
Geometry,IndexPair,2,1,2,0,1,34,1,0,0,0,0,0,,
Geometry,RhinoMath,6,12,0,5,12,213,26,0,0,0.92,1,0,Rhino.UnitSystem,
Geometry,UnitSystem,0,0,0,0,0,81,0,0,0,-1,0,0,,
Geometry,Continuity,0,0,0,0,0,105,0,0,0,-1,0,0,,
Geometry,MeshType,0,0,0,0,0,23,0,0,0,-1,0,0,,
Geometry,ActiveSpace,0,0,0,0,0,9,0,0,0,-1,0,0,,
Geometry,CoordinateSystem,0,0,0,0,0,20,0,0,0,-1,0,0,,
Geometry,ObjectMode,0,0,0,0,0,15,0,0,0,-1,0,0,,
Geometry,ObjectColorSource,0,0,0,0,0,14,0,0,0,-1,0,0,,
Geometry,ObjectPlotColorSource,0,0,0,0,0,14,0,0,0,-1,0,0,,
Geometry,ObjectPlotWeightSource,0,0,0,0,0,12,0,0,0,-1,0,0,,
Geometry,ObjectLinetypeSource,0,0,0,0,0,12,0,0,0,-1,0,0,,
Geometry,ObjectMaterialSource,0,0,0,0,0,15,0,0,0,-1,0,0,,
Geometry,DisplayMode,0,0,0,0,0,24,0,0,0,-1,0,0,,
Geometry,DistanceDisplayMode,0,0,0,0,0,15,0,0,0,-1,0,0,,
Geometry,TextDisplayAlignment,0,0,0,0,0,19,0,0,0,-1,0,0,,
Geometry,ObjectType,0,0,0,0,0,111,0,0,0,-1,0,0,,
Geometry,ObjectDecoration,0,0,0,0,0,12,0,0,0,-1,0,0,,
Geometry,LightStyle,0,0,0,0,0,34,0,0,0,-1,0,0,,
Geometry,ComponentIndexType,0,0,0,0,0,83,0,0,0,-1,0,0,,
Geometry,ComponentIndex,2,1,3,0,1,80,1,0,0,0,1,0,Rhino.Geometry.ComponentIndexType,
DocObjects,IndexPair,2,1,2,0,1,34,1,0,0,0,0,0,,
DocObjects,RhinoMath,6,12,0,5,12,213,26,0,0,0.92,1,0,Rhino.UnitSystem,
DocObjects,UnitSystem,0,0,0,0,0,81,0,0,0,-1,0,0,,
DocObjects,Continuity,0,0,0,0,0,105,0,0,0,-1,0,0,,
DocObjects,MeshType,0,0,0,0,0,23,0,0,0,-1,0,0,,
DocObjects,ActiveSpace,0,0,0,0,0,9,0,0,0,-1,0,0,,
DocObjects,CoordinateSystem,0,0,0,0,0,20,0,0,0,-1,0,0,,
DocObjects,ObjectMode,0,0,0,0,0,15,0,0,0,-1,0,0,,
DocObjects,ObjectColorSource,0,0,0,0,0,14,0,0,0,-1,0,0,,
DocObjects,ObjectPlotColorSource,0,0,0,0,0,14,0,0,0,-1,0,0,,
DocObjects,ObjectPlotWeightSource,0,0,0,0,0,12,0,0,0,-1,0,0,,
DocObjects,ObjectLinetypeSource,0,0,0,0,0,12,0,0,0,-1,0,0,,
DocObjects,ObjectMaterialSource,0,0,0,0,0,15,0,0,0,-1,0,0,,
DocObjects,DisplayMode,0,0,0,0,0,24,0,0,0,-1,0,0,,
DocObjects,DistanceDisplayMode,0,0,0,0,0,15,0,0,0,-1,0,0,,
DocObjects,TextDisplayAlignment,0,0,0,0,0,19,0,0,0,-1,0,0,,
DocObjects,ObjectType,0,0,0,0,0,111,0,0,0,-1,0,0,,
DocObjects,ObjectDecoration,0,0,0,0,0,12,0,0,0,-1,0,0,,
DocObjects,LightStyle,0,0,0,0,0,34,0,0,0,-1,0,0,,
DocObjects,ComponentIndexType,0,0,0,0,0,83,0,0,0,-1,0,0,,
DocObjects,ComponentIndex,2,1,3,0,1,80,1,0,0,0,1,0,Rhino.Geometry.ComponentIndexType,
Rhino.Geometry.Intersect,Intersection,0,14,0,0,13,1029,36,0,0,-1,19,0,Rhino.Geometry.Point3d' Rhino.Geometry.Line' Rhino.Geometry.Plane' Rhino.Geometry.Vector3d' Rhino.RhinoMath' Rhino.Geometry.Circle' Rhino.Geometry.Intersect.PlaneCircleIntersection' Rhino.Geometry.Intersect.PlaneSphereIntersection' Rhino.Geometry.Sphere' Rhino.Geometry.Intersect.LineCircleIntersection' Rhino.Geometry.Intersect.LineSphereIntersection' Rhino.Geometry.Intersect.LineCylinderIntersection' Rhino.Geometry.Cylinder' Rhino.Geometry.Intersect.SphereSphereIntersection' Rhino.Geometry.BoundingBox' Rhino.Geometry.Interval' Rhino.Geometry.Transform' Rhino.Geometry.Box' Rhino.Geometry.PlaneSurface,
Rhino.Geometry.Intersect,PlaneCircleIntersection,0,0,0,0,0,24,0,0,0,-1,0,1,,Rhino.Geometry.Intersect.Intersection
Rhino.Geometry.Intersect,PlaneSphereIntersection,0,0,0,0,0,15,0,0,0,-1,0,1,,Rhino.Geometry.Intersect.Intersection
Rhino.Geometry.Intersect,LineCircleIntersection,0,0,0,0,0,15,0,0,0,-1,0,1,,Rhino.Geometry.Intersect.Intersection
Rhino.Geometry.Intersect,LineSphereIntersection,0,0,0,0,0,15,0,0,0,-1,0,1,,Rhino.Geometry.Intersect.Intersection
Rhino.Geometry.Intersect,LineCylinderIntersection,0,0,0,0,0,19,0,0,0,-1,0,1,,Rhino.Geometry.Intersect.Intersection
Rhino.Geometry.Intersect,SphereSphereIntersection,0,0,0,0,0,19,0,0,0,-1,0,1,,Rhino.Geometry.Intersect.Intersection
Rhino.DocObjects.Custom,UserData,12,20,3,0,4,346,39,2,0,0.2,5,5,Rhino.Geometry.Transform' Rhino.FileIO.BinaryArchiveWriter' Rhino.FileIO.BinaryArchiveReader' Rhino.Runtime.HostUtils' Rhino.Runtime.CommonObject,Rhino.Runtime.HostUtils' Rhino.FileIO.ArchivableDictionary' Rhino.Collections.ArchivableDictionary' Rhino.DocObjects.Custom.UserDataList' Rhino.DocObjects.Custom.UserDictionary
Rhino.DocObjects.Custom,UnknownUserData,0,1,0,0,1,10,1,0,1,-1,0,0,,
Rhino.DocObjects.Custom,UserDataList,1,4,1,0,3,70,9,0,0,0,3,1,Rhino.Runtime.CommonObject' Rhino.DocObjects.Custom.UserData' Rhino.DocObjects.Custom.SharedUserDictionary,Rhino.Runtime.CommonObject
Rhino.DocObjects.Custom,UserDictionary,1,3,3,0,0,63,4,1,1,0.67,4,1,Rhino.Collections.ArchivableDictionary' Rhino.DocObjects.Custom.UserData' Rhino.FileIO.BinaryArchiveReader' Rhino.FileIO.BinaryArchiveWriter,Rhino.Runtime.HostUtils
Rhino.DocObjects.Custom,SharedUserDictionary,0,0,0,0,0,4,0,0,2,-1,0,2,,Rhino.Runtime.HostUtils' Rhino.DocObjects.Custom.UserDataList
Rhino.UI,LOC,0,7,0,0,7,86,7,0,0,-1,1,0,Rhino.UI.LocalizeStringPair,
Rhino.UI,DistanceDisplayMode,0,0,0,0,0,6,0,0,0,-1,0,0,,
Rhino.UI,Localization,1,13,1,0,13,200,15,0,0,0.46,2,0,Rhino.UI.LocalizationUtils' Rhino.UI.LocalizeStringPair,
Rhino.UI,LocalizeStringPair,0,1,2,0,1,10,1,0,0,-1,0,2,,Rhino.UI.LOC' Rhino.UI.Localization
Rhino.UI,LocalizationStringTable,3,11,3,0,2,581,101,0,0,0,1,2,Rhino.UI.LocalizationUtils,Rhino.UI.LocalizationUtils' Rhino.UI.AssemblyTranslations
Rhino.UI,LocalizationUtils,1,10,0,0,9,235,43,0,0,0,2,2,Rhino.UI.AssemblyTranslations' Rhino.UI.LocalizationStringTable,Rhino.UI.Localization' Rhino.UI.LocalizationStringTable
Rhino.UI,AssemblyTranslations,3,2,1,0,2,49,4,0,0,0,1,1,Rhino.UI.LocalizationStringTable,Rhino.UI.LocalizationUtils
