Namespace,Type,Method,LOC,CC,PC
Gallio.AutoCAD,IAcadPluginLocator,GetPluginPath,0,1,1
Gallio.AutoCAD,AcadLocator,GetMostRecentlyUsed,6,2,0
Gallio.AutoCAD,AcadLocator,SearchRegistry,28,1,0
Gallio.AutoCAD,AcadPluginLocator,AcadPluginLocator,8,3,2
Gallio.AutoCAD,AcadPluginLocator,GetPluginPath,31,9,1
Gallio.AutoCAD,AcadPluginLocator,TryParse,16,5,2
Gallio.AutoCAD,AcadPluginLocator,GetPlugins,19,6,0
Gallio.AutoCAD,AcadPluginLocator,GetFilesInDirectory,15,1,3
Gallio.AutoCAD,AcadPluginLocator,GetPluginVersion,12,3,1
Gallio.AutoCAD,IAcadLocator,GetMostRecentlyUsed,0,1,0
Gallio.AutoCAD.Commands,AcadCommand,AcadCommand,5,2,1
Gallio.AutoCAD.Commands,AcadCommand,GetArguments,8,3,1
Gallio.AutoCAD.Commands,AcadCommand,GetArgumentsImpl,0,1,1
Gallio.AutoCAD.Commands,AcadCommand,ToString,3,1,0
Gallio.AutoCAD.Commands,AcadCommand,ToLispExpression,13,3,1
Gallio.AutoCAD.Commands,AcadCommandRunner,BeginRun,10,4,4
Gallio.AutoCAD.Commands,AcadCommandRunner,EndRun,8,3,1
Gallio.AutoCAD.Commands,CommandTask,CommandTask,5,1,4
Gallio.AutoCAD.Commands,CommandTask,Begin,4,1,0
Gallio.AutoCAD.Commands,CommandTask,Run,15,1,0
Gallio.AutoCAD.Commands,CommandTask,CreateSTAThread,7,1,1
Gallio.AutoCAD.Commands,CommandTask,GetAcadApplication,18,3,1
Gallio.AutoCAD.Commands,CommandTask,SendCommand,13,1,2
Gallio.AutoCAD.Commands,CommandTask,GetActiveDocument,6,2,1
Gallio.AutoCAD.Commands,CommandTaskResult,CommandTaskResult,4,1,2
Gallio.AutoCAD.Commands,CommandTaskResult,Complete,11,3,1
Gallio.AutoCAD.Commands,CommandTaskResult,Get,15,3,0
Gallio.AutoCAD.Commands,IOleMessageFilter,HandleInComingCall,0,1,4
Gallio.AutoCAD.Commands,IOleMessageFilter,RetryRejectedCall,0,1,3
Gallio.AutoCAD.Commands,IOleMessageFilter,MessagePending,0,1,3
Gallio.AutoCAD.Commands,MessageFilter,MessageFilter,3,1,1
Gallio.AutoCAD.Commands,MessageFilter,Register,5,1,1
Gallio.AutoCAD.Commands,MessageFilter,Dispose,4,1,0
Gallio.AutoCAD.Commands,MessageFilter,HandleInComingCall,5,2,4
Gallio.AutoCAD.Commands,MessageFilter,RetryRejectedCall,11,4,3
Gallio.AutoCAD.Commands,MessageFilter,MessagePending,5,2,3
Gallio.AutoCAD.Commands,MessageFilter,CoRegisterMessageFilter,0,1,2
Gallio.AutoCAD.Commands,CreateEndpointAndWaitCommand,CreateEndpointAndWaitCommand,6,2,2
Gallio.AutoCAD.Commands,CreateEndpointAndWaitCommand,GetArgumentsImpl,4,1,1
Gallio.AutoCAD.Commands,IAcadCommandRunner,BeginRun,0,1,4
Gallio.AutoCAD.Commands,IAcadCommandRunner,EndRun,0,1,1
Gallio.AutoCAD.Commands,NetLoadCommand,NetLoadCommand,8,3,2
Gallio.AutoCAD.Commands,NetLoadCommand,GetArgumentsImpl,5,1,1
Gallio.AutoCAD.Commands,NetLoadCommand,GetAcadVersion,11,1,1
Gallio.AutoCAD.Isolation,AcadTestIsolationContext,AcadTestIsolationContext,8,3,2
Gallio.AutoCAD.Isolation,AcadTestIsolationContext,BeginBatchImpl,4,1,1
Gallio.AutoCAD.Isolation,AcadTestIsolationContext,RunIsolatedTaskImpl,9,2,3
Gallio.AutoCAD.Isolation,Batch,Batch,4,1,2
Gallio.AutoCAD.Isolation,Batch,GetTestIsolationServer,21,2,1
Gallio.AutoCAD.Isolation,Batch,Dispose,12,3,0
Gallio.AutoCAD.Isolation,AcadTestIsolationProvider,AcadTestIsolationProvider,5,2,1
Gallio.AutoCAD.Isolation,AcadTestIsolationProvider,CreateContextImpl,4,1,2
Gallio.AutoCAD.Preferences,AcadPreferenceManager,AcadPreferenceManager,5,2,1
Gallio.AutoCAD.ProcessManagement,AcadProcessBase,AcadProcessBase,11,4,3
Gallio.AutoCAD.ProcessManagement,AcadProcessBase,Dispose,4,1,0
Gallio.AutoCAD.ProcessManagement,AcadProcessBase,Dispose,20,3,1
Gallio.AutoCAD.ProcessManagement,AcadProcessBase,Start,12,4,3
Gallio.AutoCAD.ProcessManagement,AcadProcessBase,NetLoadPlugin,6,1,1
Gallio.AutoCAD.ProcessManagement,AcadProcessBase,StartProcess,0,1,1
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,AcadProcessFactory,26,9,8
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,CreateProcess,14,3,1
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,GetExistingAcadProcess,17,3,0
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,AttachToProcess,3,1,1
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,CreateNewProcess,17,2,3
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,ValidateExecutablePath,8,4,1
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,ValidateWorkingDirectory,8,4,1
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,GetStartupAction,14,4,2
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,GetAttachOption,9,3,1
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,GetExecutable,8,3,3
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,GetWorkingDirectory,4,1,1
Gallio.AutoCAD.ProcessManagement,AcadProcessFactory,GetArguments,4,1,1
Gallio.AutoCAD.ProcessManagement,CreatedAcadProcess,CreatedAcadProcess,13,5,6
Gallio.AutoCAD.ProcessManagement,CreatedAcadProcess,StartProcess,6,2,1
Gallio.AutoCAD.ProcessManagement,CreatedAcadProcess,StartProcessWithDebugger,7,2,1
Gallio.AutoCAD.ProcessManagement,CreatedAcadProcess,Dispose,14,4,1
Gallio.AutoCAD.ProcessManagement,ExistingAcadProcess,ExistingAcadProcess,5,2,4
Gallio.AutoCAD.ProcessManagement,ExistingAcadProcess,Dispose,8,2,1
Gallio.AutoCAD.ProcessManagement,ExistingAcadProcess,StartProcess,3,1,1
Gallio.AutoCAD.ProcessManagement,IAcadProcess,Start,0,1,3
Gallio.AutoCAD.ProcessManagement,IAcadProcessFactory,CreateProcess,0,1,1
